/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "core-x86.pb-c.h"
void   user_x86_regs_entry__init
                     (UserX86RegsEntry         *message)
{
  static UserX86RegsEntry init_value = USER_X86_REGS_ENTRY__INIT;
  *message = init_value;
}
size_t user_x86_regs_entry__get_packed_size
                     (const UserX86RegsEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_regs_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user_x86_regs_entry__pack
                     (const UserX86RegsEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_regs_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user_x86_regs_entry__pack_to_buffer
                     (const UserX86RegsEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_regs_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UserX86RegsEntry *
       user_x86_regs_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UserX86RegsEntry *)
     protobuf_c_message_unpack (&user_x86_regs_entry__descriptor,
                                allocator, len, data);
}
void   user_x86_regs_entry__free_unpacked
                     (UserX86RegsEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_regs_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   user_x86_xsave_entry__init
                     (UserX86XsaveEntry         *message)
{
  static UserX86XsaveEntry init_value = USER_X86_XSAVE_ENTRY__INIT;
  *message = init_value;
}
size_t user_x86_xsave_entry__get_packed_size
                     (const UserX86XsaveEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_xsave_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user_x86_xsave_entry__pack
                     (const UserX86XsaveEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_xsave_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user_x86_xsave_entry__pack_to_buffer
                     (const UserX86XsaveEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_xsave_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UserX86XsaveEntry *
       user_x86_xsave_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UserX86XsaveEntry *)
     protobuf_c_message_unpack (&user_x86_xsave_entry__descriptor,
                                allocator, len, data);
}
void   user_x86_xsave_entry__free_unpacked
                     (UserX86XsaveEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_xsave_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   user_x86_fpregs_entry__init
                     (UserX86FpregsEntry         *message)
{
  static UserX86FpregsEntry init_value = USER_X86_FPREGS_ENTRY__INIT;
  *message = init_value;
}
size_t user_x86_fpregs_entry__get_packed_size
                     (const UserX86FpregsEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_fpregs_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user_x86_fpregs_entry__pack
                     (const UserX86FpregsEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_fpregs_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user_x86_fpregs_entry__pack_to_buffer
                     (const UserX86FpregsEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_fpregs_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UserX86FpregsEntry *
       user_x86_fpregs_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UserX86FpregsEntry *)
     protobuf_c_message_unpack (&user_x86_fpregs_entry__descriptor,
                                allocator, len, data);
}
void   user_x86_fpregs_entry__free_unpacked
                     (UserX86FpregsEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &user_x86_fpregs_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   thread_info_x86__init
                     (ThreadInfoX86         *message)
{
  static ThreadInfoX86 init_value = THREAD_INFO_X86__INIT;
  *message = init_value;
}
size_t thread_info_x86__get_packed_size
                     (const ThreadInfoX86 *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &thread_info_x86__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t thread_info_x86__pack
                     (const ThreadInfoX86 *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &thread_info_x86__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t thread_info_x86__pack_to_buffer
                     (const ThreadInfoX86 *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &thread_info_x86__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ThreadInfoX86 *
       thread_info_x86__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ThreadInfoX86 *)
     protobuf_c_message_unpack (&thread_info_x86__descriptor,
                                allocator, len, data);
}
void   thread_info_x86__free_unpacked
                     (ThreadInfoX86 *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &thread_info_x86__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor user_x86_regs_entry__field_descriptors[27] =
{
  {
    "r15",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, r15),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r14",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, r14),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r13",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, r13),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r12",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, r12),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bp",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, bp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bx",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, bx),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r11",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, r11),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r10",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, r10),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r9",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, r9),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "r8",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, r8),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ax",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, ax),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cx",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, cx),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dx",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, dx),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "si",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, si),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "di",
    15,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, di),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "orig_ax",
    16,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, orig_ax),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    17,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, ip),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cs",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, cs),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    19,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, flags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sp",
    20,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, sp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ss",
    21,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, ss),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fs_base",
    22,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, fs_base),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gs_base",
    23,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, gs_base),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ds",
    24,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, ds),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "es",
    25,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, es),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fs",
    26,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, fs),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gs",
    27,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86RegsEntry, gs),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user_x86_regs_entry__field_indices_by_name[] = {
  10,   /* field[10] = ax */
  4,   /* field[4] = bp */
  5,   /* field[5] = bx */
  17,   /* field[17] = cs */
  11,   /* field[11] = cx */
  14,   /* field[14] = di */
  23,   /* field[23] = ds */
  12,   /* field[12] = dx */
  24,   /* field[24] = es */
  18,   /* field[18] = flags */
  25,   /* field[25] = fs */
  21,   /* field[21] = fs_base */
  26,   /* field[26] = gs */
  22,   /* field[22] = gs_base */
  16,   /* field[16] = ip */
  15,   /* field[15] = orig_ax */
  7,   /* field[7] = r10 */
  6,   /* field[6] = r11 */
  3,   /* field[3] = r12 */
  2,   /* field[2] = r13 */
  1,   /* field[1] = r14 */
  0,   /* field[0] = r15 */
  9,   /* field[9] = r8 */
  8,   /* field[8] = r9 */
  13,   /* field[13] = si */
  19,   /* field[19] = sp */
  20,   /* field[20] = ss */
};
static const ProtobufCIntRange user_x86_regs_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 27 }
};
const ProtobufCMessageDescriptor user_x86_regs_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "user_x86_regs_entry",
  "UserX86RegsEntry",
  "UserX86RegsEntry",
  "",
  sizeof(UserX86RegsEntry),
  27,
  user_x86_regs_entry__field_descriptors,
  user_x86_regs_entry__field_indices_by_name,
  1,  user_x86_regs_entry__number_ranges,
  (ProtobufCMessageInit) user_x86_regs_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor user_x86_xsave_entry__field_descriptors[2] =
{
  {
    "xstate_bv",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86XsaveEntry, xstate_bv),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ymmh_space",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(UserX86XsaveEntry, n_ymmh_space),
    PROTOBUF_C_OFFSETOF(UserX86XsaveEntry, ymmh_space),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user_x86_xsave_entry__field_indices_by_name[] = {
  0,   /* field[0] = xstate_bv */
  1,   /* field[1] = ymmh_space */
};
static const ProtobufCIntRange user_x86_xsave_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor user_x86_xsave_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "user_x86_xsave_entry",
  "UserX86XsaveEntry",
  "UserX86XsaveEntry",
  "",
  sizeof(UserX86XsaveEntry),
  2,
  user_x86_xsave_entry__field_descriptors,
  user_x86_xsave_entry__field_indices_by_name,
  1,  user_x86_xsave_entry__number_ranges,
  (ProtobufCMessageInit) user_x86_xsave_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor user_x86_fpregs_entry__field_descriptors[12] =
{
  {
    "cwd",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, cwd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "swd",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, swd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "twd",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, twd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fop",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, fop),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rip",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, rip),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rdp",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, rdp),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mxcsr",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, mxcsr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mxcsr_mask",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, mxcsr_mask),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "st_space",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, n_st_space),
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, st_space),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xmm_space",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, n_xmm_space),
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, xmm_space),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "padding",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, n_padding),
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, padding),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "xsave",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UserX86FpregsEntry, xsave),
    &user_x86_xsave_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user_x86_fpregs_entry__field_indices_by_name[] = {
  0,   /* field[0] = cwd */
  3,   /* field[3] = fop */
  6,   /* field[6] = mxcsr */
  7,   /* field[7] = mxcsr_mask */
  10,   /* field[10] = padding */
  5,   /* field[5] = rdp */
  4,   /* field[4] = rip */
  8,   /* field[8] = st_space */
  1,   /* field[1] = swd */
  2,   /* field[2] = twd */
  9,   /* field[9] = xmm_space */
  11,   /* field[11] = xsave */
};
static const ProtobufCIntRange user_x86_fpregs_entry__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 13, 11 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor user_x86_fpregs_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "user_x86_fpregs_entry",
  "UserX86FpregsEntry",
  "UserX86FpregsEntry",
  "",
  sizeof(UserX86FpregsEntry),
  12,
  user_x86_fpregs_entry__field_descriptors,
  user_x86_fpregs_entry__field_indices_by_name,
  2,  user_x86_fpregs_entry__number_ranges,
  (ProtobufCMessageInit) user_x86_fpregs_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor thread_info_x86__field_descriptors[3] =
{
  {
    "clear_tid_addr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ThreadInfoX86, clear_tid_addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gpregs",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ThreadInfoX86, gpregs),
    &user_x86_regs_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fpregs",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ThreadInfoX86, fpregs),
    &user_x86_fpregs_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned thread_info_x86__field_indices_by_name[] = {
  0,   /* field[0] = clear_tid_addr */
  2,   /* field[2] = fpregs */
  1,   /* field[1] = gpregs */
};
static const ProtobufCIntRange thread_info_x86__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor thread_info_x86__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "thread_info_x86",
  "ThreadInfoX86",
  "ThreadInfoX86",
  "",
  sizeof(ThreadInfoX86),
  3,
  thread_info_x86__field_descriptors,
  thread_info_x86__field_indices_by_name,
  1,  thread_info_x86__number_ranges,
  (ProtobufCMessageInit) thread_info_x86__init,
  NULL,NULL,NULL    /* reserved[123] */
};
