/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_core_2dx86_2eproto__INCLUDED
#define PROTOBUF_C_core_2dx86_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "opts.pb-c.h"

typedef struct _UserX86RegsEntry UserX86RegsEntry;
typedef struct _UserX86XsaveEntry UserX86XsaveEntry;
typedef struct _UserX86FpregsEntry UserX86FpregsEntry;
typedef struct _ThreadInfoX86 ThreadInfoX86;


/* --- enums --- */


/* --- messages --- */

struct  _UserX86RegsEntry
{
  ProtobufCMessage base;
  uint64_t r15;
  uint64_t r14;
  uint64_t r13;
  uint64_t r12;
  uint64_t bp;
  uint64_t bx;
  uint64_t r11;
  uint64_t r10;
  uint64_t r9;
  uint64_t r8;
  uint64_t ax;
  uint64_t cx;
  uint64_t dx;
  uint64_t si;
  uint64_t di;
  uint64_t orig_ax;
  uint64_t ip;
  uint64_t cs;
  uint64_t flags;
  uint64_t sp;
  uint64_t ss;
  uint64_t fs_base;
  uint64_t gs_base;
  uint64_t ds;
  uint64_t es;
  uint64_t fs;
  uint64_t gs;
};
#define USER_X86_REGS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&user_x86_regs_entry__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  _UserX86XsaveEntry
{
  ProtobufCMessage base;
  uint64_t xstate_bv;
  size_t n_ymmh_space;
  uint32_t *ymmh_space;
};
#define USER_X86_XSAVE_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&user_x86_xsave_entry__descriptor) \
    , 0, 0,NULL }


struct  _UserX86FpregsEntry
{
  ProtobufCMessage base;
  uint32_t cwd;
  uint32_t swd;
  uint32_t twd;
  uint32_t fop;
  uint64_t rip;
  uint64_t rdp;
  uint32_t mxcsr;
  uint32_t mxcsr_mask;
  size_t n_st_space;
  uint32_t *st_space;
  size_t n_xmm_space;
  uint32_t *xmm_space;
  size_t n_padding;
  uint32_t *padding;
  UserX86XsaveEntry *xsave;
};
#define USER_X86_FPREGS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&user_x86_fpregs_entry__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0,NULL, 0,NULL, 0,NULL, NULL }


struct  _ThreadInfoX86
{
  ProtobufCMessage base;
  uint64_t clear_tid_addr;
  UserX86RegsEntry *gpregs;
  UserX86FpregsEntry *fpregs;
};
#define THREAD_INFO_X86__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&thread_info_x86__descriptor) \
    , 0, NULL, NULL }


/* UserX86RegsEntry methods */
void   user_x86_regs_entry__init
                     (UserX86RegsEntry         *message);
size_t user_x86_regs_entry__get_packed_size
                     (const UserX86RegsEntry   *message);
size_t user_x86_regs_entry__pack
                     (const UserX86RegsEntry   *message,
                      uint8_t             *out);
size_t user_x86_regs_entry__pack_to_buffer
                     (const UserX86RegsEntry   *message,
                      ProtobufCBuffer     *buffer);
UserX86RegsEntry *
       user_x86_regs_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   user_x86_regs_entry__free_unpacked
                     (UserX86RegsEntry *message,
                      ProtobufCAllocator *allocator);
/* UserX86XsaveEntry methods */
void   user_x86_xsave_entry__init
                     (UserX86XsaveEntry         *message);
size_t user_x86_xsave_entry__get_packed_size
                     (const UserX86XsaveEntry   *message);
size_t user_x86_xsave_entry__pack
                     (const UserX86XsaveEntry   *message,
                      uint8_t             *out);
size_t user_x86_xsave_entry__pack_to_buffer
                     (const UserX86XsaveEntry   *message,
                      ProtobufCBuffer     *buffer);
UserX86XsaveEntry *
       user_x86_xsave_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   user_x86_xsave_entry__free_unpacked
                     (UserX86XsaveEntry *message,
                      ProtobufCAllocator *allocator);
/* UserX86FpregsEntry methods */
void   user_x86_fpregs_entry__init
                     (UserX86FpregsEntry         *message);
size_t user_x86_fpregs_entry__get_packed_size
                     (const UserX86FpregsEntry   *message);
size_t user_x86_fpregs_entry__pack
                     (const UserX86FpregsEntry   *message,
                      uint8_t             *out);
size_t user_x86_fpregs_entry__pack_to_buffer
                     (const UserX86FpregsEntry   *message,
                      ProtobufCBuffer     *buffer);
UserX86FpregsEntry *
       user_x86_fpregs_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   user_x86_fpregs_entry__free_unpacked
                     (UserX86FpregsEntry *message,
                      ProtobufCAllocator *allocator);
/* ThreadInfoX86 methods */
void   thread_info_x86__init
                     (ThreadInfoX86         *message);
size_t thread_info_x86__get_packed_size
                     (const ThreadInfoX86   *message);
size_t thread_info_x86__pack
                     (const ThreadInfoX86   *message,
                      uint8_t             *out);
size_t thread_info_x86__pack_to_buffer
                     (const ThreadInfoX86   *message,
                      ProtobufCBuffer     *buffer);
ThreadInfoX86 *
       thread_info_x86__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   thread_info_x86__free_unpacked
                     (ThreadInfoX86 *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*UserX86RegsEntry_Closure)
                 (const UserX86RegsEntry *message,
                  void *closure_data);
typedef void (*UserX86XsaveEntry_Closure)
                 (const UserX86XsaveEntry *message,
                  void *closure_data);
typedef void (*UserX86FpregsEntry_Closure)
                 (const UserX86FpregsEntry *message,
                  void *closure_data);
typedef void (*ThreadInfoX86_Closure)
                 (const ThreadInfoX86 *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor user_x86_regs_entry__descriptor;
extern const ProtobufCMessageDescriptor user_x86_xsave_entry__descriptor;
extern const ProtobufCMessageDescriptor user_x86_fpregs_entry__descriptor;
extern const ProtobufCMessageDescriptor thread_info_x86__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_core_2dx86_2eproto__INCLUDED */
