/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_cpuinfo_2eproto__INCLUDED
#define PROTOBUF_C_cpuinfo_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _CpuinfoX86Entry CpuinfoX86Entry;
typedef struct _CpuinfoPpc64Entry CpuinfoPpc64Entry;
typedef struct _CpuinfoEntry CpuinfoEntry;


/* --- enums --- */

typedef enum _CpuinfoX86Entry__Vendor {
  CPUINFO_X86_ENTRY__VENDOR__UNKNOWN = 0,
  CPUINFO_X86_ENTRY__VENDOR__INTEL = 1,
  CPUINFO_X86_ENTRY__VENDOR__AMD = 2
} CpuinfoX86Entry__Vendor;
typedef enum _CpuinfoPpc64Entry__Endianness {
  CPUINFO_PPC64_ENTRY__ENDIANNESS__BIGENDIAN = 0,
  CPUINFO_PPC64_ENTRY__ENDIANNESS__LITTLEENDIAN = 1
} CpuinfoPpc64Entry__Endianness;

/* --- messages --- */

struct  _CpuinfoX86Entry
{
  ProtobufCMessage base;
  CpuinfoX86Entry__Vendor vendor_id;
  uint32_t cpu_family;
  uint32_t model;
  uint32_t stepping;
  uint32_t capability_ver;
  size_t n_capability;
  uint32_t *capability;
  char *model_id;
};
#define CPUINFO_X86_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cpuinfo_x86_entry__descriptor) \
    , 0, 0, 0, 0, 0, 0,NULL, NULL }


struct  _CpuinfoPpc64Entry
{
  ProtobufCMessage base;
  CpuinfoPpc64Entry__Endianness endian;
  size_t n_hwcap;
  uint64_t *hwcap;
};
#define CPUINFO_PPC64_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cpuinfo_ppc64_entry__descriptor) \
    , 0, 0,NULL }


struct  _CpuinfoEntry
{
  ProtobufCMessage base;
  size_t n_x86_entry;
  CpuinfoX86Entry **x86_entry;
  size_t n_ppc64_entry;
  CpuinfoPpc64Entry **ppc64_entry;
};
#define CPUINFO_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cpuinfo_entry__descriptor) \
    , 0,NULL, 0,NULL }


/* CpuinfoX86Entry methods */
void   cpuinfo_x86_entry__init
                     (CpuinfoX86Entry         *message);
size_t cpuinfo_x86_entry__get_packed_size
                     (const CpuinfoX86Entry   *message);
size_t cpuinfo_x86_entry__pack
                     (const CpuinfoX86Entry   *message,
                      uint8_t             *out);
size_t cpuinfo_x86_entry__pack_to_buffer
                     (const CpuinfoX86Entry   *message,
                      ProtobufCBuffer     *buffer);
CpuinfoX86Entry *
       cpuinfo_x86_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cpuinfo_x86_entry__free_unpacked
                     (CpuinfoX86Entry *message,
                      ProtobufCAllocator *allocator);
/* CpuinfoPpc64Entry methods */
void   cpuinfo_ppc64_entry__init
                     (CpuinfoPpc64Entry         *message);
size_t cpuinfo_ppc64_entry__get_packed_size
                     (const CpuinfoPpc64Entry   *message);
size_t cpuinfo_ppc64_entry__pack
                     (const CpuinfoPpc64Entry   *message,
                      uint8_t             *out);
size_t cpuinfo_ppc64_entry__pack_to_buffer
                     (const CpuinfoPpc64Entry   *message,
                      ProtobufCBuffer     *buffer);
CpuinfoPpc64Entry *
       cpuinfo_ppc64_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cpuinfo_ppc64_entry__free_unpacked
                     (CpuinfoPpc64Entry *message,
                      ProtobufCAllocator *allocator);
/* CpuinfoEntry methods */
void   cpuinfo_entry__init
                     (CpuinfoEntry         *message);
size_t cpuinfo_entry__get_packed_size
                     (const CpuinfoEntry   *message);
size_t cpuinfo_entry__pack
                     (const CpuinfoEntry   *message,
                      uint8_t             *out);
size_t cpuinfo_entry__pack_to_buffer
                     (const CpuinfoEntry   *message,
                      ProtobufCBuffer     *buffer);
CpuinfoEntry *
       cpuinfo_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cpuinfo_entry__free_unpacked
                     (CpuinfoEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CpuinfoX86Entry_Closure)
                 (const CpuinfoX86Entry *message,
                  void *closure_data);
typedef void (*CpuinfoPpc64Entry_Closure)
                 (const CpuinfoPpc64Entry *message,
                  void *closure_data);
typedef void (*CpuinfoEntry_Closure)
                 (const CpuinfoEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cpuinfo_x86_entry__descriptor;
extern const ProtobufCEnumDescriptor    cpuinfo_x86_entry__vendor__descriptor;
extern const ProtobufCMessageDescriptor cpuinfo_ppc64_entry__descriptor;
extern const ProtobufCEnumDescriptor    cpuinfo_ppc64_entry__endianness__descriptor;
extern const ProtobufCMessageDescriptor cpuinfo_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_cpuinfo_2eproto__INCLUDED */
