/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_eventfd_2eproto__INCLUDED
#define PROTOBUF_C_eventfd_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "fown.pb-c.h"

typedef struct _EventfdFileEntry EventfdFileEntry;


/* --- enums --- */


/* --- messages --- */

struct  _EventfdFileEntry
{
  ProtobufCMessage base;
  uint32_t id;
  uint32_t flags;
  FownEntry *fown;
  uint64_t counter;
};
#define EVENTFD_FILE_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&eventfd_file_entry__descriptor) \
    , 0, 0, NULL, 0 }


/* EventfdFileEntry methods */
void   eventfd_file_entry__init
                     (EventfdFileEntry         *message);
size_t eventfd_file_entry__get_packed_size
                     (const EventfdFileEntry   *message);
size_t eventfd_file_entry__pack
                     (const EventfdFileEntry   *message,
                      uint8_t             *out);
size_t eventfd_file_entry__pack_to_buffer
                     (const EventfdFileEntry   *message,
                      ProtobufCBuffer     *buffer);
EventfdFileEntry *
       eventfd_file_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   eventfd_file_entry__free_unpacked
                     (EventfdFileEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*EventfdFileEntry_Closure)
                 (const EventfdFileEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor eventfd_file_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_eventfd_2eproto__INCLUDED */
