/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_ext_2dfile_2eproto__INCLUDED
#define PROTOBUF_C_ext_2dfile_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "fown.pb-c.h"

typedef struct _ExtFileEntry ExtFileEntry;


/* --- enums --- */


/* --- messages --- */

struct  _ExtFileEntry
{
  ProtobufCMessage base;
  uint32_t id;
  FownEntry *fown;
};
#define EXT_FILE_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ext_file_entry__descriptor) \
    , 0, NULL }


/* ExtFileEntry methods */
void   ext_file_entry__init
                     (ExtFileEntry         *message);
size_t ext_file_entry__get_packed_size
                     (const ExtFileEntry   *message);
size_t ext_file_entry__pack
                     (const ExtFileEntry   *message,
                      uint8_t             *out);
size_t ext_file_entry__pack_to_buffer
                     (const ExtFileEntry   *message,
                      ProtobufCBuffer     *buffer);
ExtFileEntry *
       ext_file_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ext_file_entry__free_unpacked
                     (ExtFileEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ExtFileEntry_Closure)
                 (const ExtFileEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ext_file_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_ext_2dfile_2eproto__INCLUDED */
