/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_fdinfo_2eproto__INCLUDED
#define PROTOBUF_C_fdinfo_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _FdinfoEntry FdinfoEntry;


/* --- enums --- */

typedef enum _FdTypes {
  FD_TYPES__UND = 0,
  FD_TYPES__REG = 1,
  FD_TYPES__PIPE = 2,
  FD_TYPES__FIFO = 3,
  FD_TYPES__INETSK = 4,
  FD_TYPES__UNIXSK = 5,
  FD_TYPES__EVENTFD = 6,
  FD_TYPES__EVENTPOLL = 7,
  FD_TYPES__INOTIFY = 8,
  FD_TYPES__SIGNALFD = 9,
  FD_TYPES__PACKETSK = 10,
  FD_TYPES__TTY = 11,
  FD_TYPES__FANOTIFY = 12,
  FD_TYPES__NETLINKSK = 13,
  FD_TYPES__NS = 14,
  FD_TYPES__TUNF = 15,
  FD_TYPES__EXT = 16,
  FD_TYPES__TIMERFD = 17
} FdTypes;

/* --- messages --- */

struct  _FdinfoEntry
{
  ProtobufCMessage base;
  uint32_t id;
  uint32_t flags;
  FdTypes type;
  uint32_t fd;
};
#define FDINFO_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fdinfo_entry__descriptor) \
    , 0, 0, 0, 0 }


/* FdinfoEntry methods */
void   fdinfo_entry__init
                     (FdinfoEntry         *message);
size_t fdinfo_entry__get_packed_size
                     (const FdinfoEntry   *message);
size_t fdinfo_entry__pack
                     (const FdinfoEntry   *message,
                      uint8_t             *out);
size_t fdinfo_entry__pack_to_buffer
                     (const FdinfoEntry   *message,
                      ProtobufCBuffer     *buffer);
FdinfoEntry *
       fdinfo_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fdinfo_entry__free_unpacked
                     (FdinfoEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FdinfoEntry_Closure)
                 (const FdinfoEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    fd_types__descriptor;
extern const ProtobufCMessageDescriptor fdinfo_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_fdinfo_2eproto__INCLUDED */
