/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "fdinfo.pb-c.h"
void   fdinfo_entry__init
                     (FdinfoEntry         *message)
{
  static FdinfoEntry init_value = FDINFO_ENTRY__INIT;
  *message = init_value;
}
size_t fdinfo_entry__get_packed_size
                     (const FdinfoEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fdinfo_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fdinfo_entry__pack
                     (const FdinfoEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fdinfo_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fdinfo_entry__pack_to_buffer
                     (const FdinfoEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fdinfo_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FdinfoEntry *
       fdinfo_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FdinfoEntry *)
     protobuf_c_message_unpack (&fdinfo_entry__descriptor,
                                allocator, len, data);
}
void   fdinfo_entry__free_unpacked
                     (FdinfoEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fdinfo_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor fdinfo_entry__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FdinfoEntry, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FdinfoEntry, flags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FdinfoEntry, type),
    &fd_types__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fd",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FdinfoEntry, fd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fdinfo_entry__field_indices_by_name[] = {
  3,   /* field[3] = fd */
  1,   /* field[1] = flags */
  0,   /* field[0] = id */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange fdinfo_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor fdinfo_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "fdinfo_entry",
  "FdinfoEntry",
  "FdinfoEntry",
  "",
  sizeof(FdinfoEntry),
  4,
  fdinfo_entry__field_descriptors,
  fdinfo_entry__field_indices_by_name,
  1,  fdinfo_entry__number_ranges,
  (ProtobufCMessageInit) fdinfo_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue fd_types__enum_values_by_number[18] =
{
  { "UND", "FD_TYPES__UND", 0 },
  { "REG", "FD_TYPES__REG", 1 },
  { "PIPE", "FD_TYPES__PIPE", 2 },
  { "FIFO", "FD_TYPES__FIFO", 3 },
  { "INETSK", "FD_TYPES__INETSK", 4 },
  { "UNIXSK", "FD_TYPES__UNIXSK", 5 },
  { "EVENTFD", "FD_TYPES__EVENTFD", 6 },
  { "EVENTPOLL", "FD_TYPES__EVENTPOLL", 7 },
  { "INOTIFY", "FD_TYPES__INOTIFY", 8 },
  { "SIGNALFD", "FD_TYPES__SIGNALFD", 9 },
  { "PACKETSK", "FD_TYPES__PACKETSK", 10 },
  { "TTY", "FD_TYPES__TTY", 11 },
  { "FANOTIFY", "FD_TYPES__FANOTIFY", 12 },
  { "NETLINKSK", "FD_TYPES__NETLINKSK", 13 },
  { "NS", "FD_TYPES__NS", 14 },
  { "TUNF", "FD_TYPES__TUNF", 15 },
  { "EXT", "FD_TYPES__EXT", 16 },
  { "TIMERFD", "FD_TYPES__TIMERFD", 17 },
};
static const ProtobufCIntRange fd_types__value_ranges[] = {
{0, 0},{0, 18}
};
const ProtobufCEnumValueIndex fd_types__enum_values_by_name[18] =
{
  { "EVENTFD", 6 },
  { "EVENTPOLL", 7 },
  { "EXT", 16 },
  { "FANOTIFY", 12 },
  { "FIFO", 3 },
  { "INETSK", 4 },
  { "INOTIFY", 8 },
  { "NETLINKSK", 13 },
  { "NS", 14 },
  { "PACKETSK", 10 },
  { "PIPE", 2 },
  { "REG", 1 },
  { "SIGNALFD", 9 },
  { "TIMERFD", 17 },
  { "TTY", 11 },
  { "TUNF", 15 },
  { "UND", 0 },
  { "UNIXSK", 5 },
};
const ProtobufCEnumDescriptor fd_types__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "fd_types",
  "fd_types",
  "FdTypes",
  "",
  18,
  fd_types__enum_values_by_number,
  18,
  fd_types__enum_values_by_name,
  1,
  fd_types__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
