/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_fifo_2eproto__INCLUDED
#define PROTOBUF_C_fifo_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _FifoEntry FifoEntry;


/* --- enums --- */


/* --- messages --- */

struct  _FifoEntry
{
  ProtobufCMessage base;
  uint32_t id;
  uint32_t pipe_id;
};
#define FIFO_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fifo_entry__descriptor) \
    , 0, 0 }


/* FifoEntry methods */
void   fifo_entry__init
                     (FifoEntry         *message);
size_t fifo_entry__get_packed_size
                     (const FifoEntry   *message);
size_t fifo_entry__pack
                     (const FifoEntry   *message,
                      uint8_t             *out);
size_t fifo_entry__pack_to_buffer
                     (const FifoEntry   *message,
                      ProtobufCBuffer     *buffer);
FifoEntry *
       fifo_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fifo_entry__free_unpacked
                     (FifoEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FifoEntry_Closure)
                 (const FifoEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fifo_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_fifo_2eproto__INCLUDED */
