/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_file_2dlock_2eproto__INCLUDED
#define PROTOBUF_C_file_2dlock_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _FileLockEntry FileLockEntry;


/* --- enums --- */


/* --- messages --- */

struct  _FileLockEntry
{
  ProtobufCMessage base;
  uint32_t flag;
  uint32_t type;
  int32_t pid;
  int32_t fd;
  int64_t start;
  int64_t len;
};
#define FILE_LOCK_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&file_lock_entry__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


/* FileLockEntry methods */
void   file_lock_entry__init
                     (FileLockEntry         *message);
size_t file_lock_entry__get_packed_size
                     (const FileLockEntry   *message);
size_t file_lock_entry__pack
                     (const FileLockEntry   *message,
                      uint8_t             *out);
size_t file_lock_entry__pack_to_buffer
                     (const FileLockEntry   *message,
                      ProtobufCBuffer     *buffer);
FileLockEntry *
       file_lock_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   file_lock_entry__free_unpacked
                     (FileLockEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FileLockEntry_Closure)
                 (const FileLockEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor file_lock_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_file_2dlock_2eproto__INCLUDED */
