/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_fown_2eproto__INCLUDED
#define PROTOBUF_C_fown_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _FownEntry FownEntry;


/* --- enums --- */


/* --- messages --- */

struct  _FownEntry
{
  ProtobufCMessage base;
  uint32_t uid;
  uint32_t euid;
  uint32_t signum;
  uint32_t pid_type;
  uint32_t pid;
};
#define FOWN_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&fown_entry__descriptor) \
    , 0, 0, 0, 0, 0 }


/* FownEntry methods */
void   fown_entry__init
                     (FownEntry         *message);
size_t fown_entry__get_packed_size
                     (const FownEntry   *message);
size_t fown_entry__pack
                     (const FownEntry   *message,
                      uint8_t             *out);
size_t fown_entry__pack_to_buffer
                     (const FownEntry   *message,
                      ProtobufCBuffer     *buffer);
FownEntry *
       fown_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   fown_entry__free_unpacked
                     (FownEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*FownEntry_Closure)
                 (const FownEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor fown_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_fown_2eproto__INCLUDED */
