/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "fsnotify.pb-c.h"
void   inotify_wd_entry__init
                     (InotifyWdEntry         *message)
{
  static InotifyWdEntry init_value = INOTIFY_WD_ENTRY__INIT;
  *message = init_value;
}
size_t inotify_wd_entry__get_packed_size
                     (const InotifyWdEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inotify_wd_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t inotify_wd_entry__pack
                     (const InotifyWdEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inotify_wd_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t inotify_wd_entry__pack_to_buffer
                     (const InotifyWdEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inotify_wd_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InotifyWdEntry *
       inotify_wd_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InotifyWdEntry *)
     protobuf_c_message_unpack (&inotify_wd_entry__descriptor,
                                allocator, len, data);
}
void   inotify_wd_entry__free_unpacked
                     (InotifyWdEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inotify_wd_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   inotify_file_entry__init
                     (InotifyFileEntry         *message)
{
  static InotifyFileEntry init_value = INOTIFY_FILE_ENTRY__INIT;
  *message = init_value;
}
size_t inotify_file_entry__get_packed_size
                     (const InotifyFileEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inotify_file_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t inotify_file_entry__pack
                     (const InotifyFileEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inotify_file_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t inotify_file_entry__pack_to_buffer
                     (const InotifyFileEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inotify_file_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InotifyFileEntry *
       inotify_file_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InotifyFileEntry *)
     protobuf_c_message_unpack (&inotify_file_entry__descriptor,
                                allocator, len, data);
}
void   inotify_file_entry__free_unpacked
                     (InotifyFileEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inotify_file_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fanotify_inode_mark_entry__init
                     (FanotifyInodeMarkEntry         *message)
{
  static FanotifyInodeMarkEntry init_value = FANOTIFY_INODE_MARK_ENTRY__INIT;
  *message = init_value;
}
size_t fanotify_inode_mark_entry__get_packed_size
                     (const FanotifyInodeMarkEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_inode_mark_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fanotify_inode_mark_entry__pack
                     (const FanotifyInodeMarkEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_inode_mark_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fanotify_inode_mark_entry__pack_to_buffer
                     (const FanotifyInodeMarkEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_inode_mark_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FanotifyInodeMarkEntry *
       fanotify_inode_mark_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FanotifyInodeMarkEntry *)
     protobuf_c_message_unpack (&fanotify_inode_mark_entry__descriptor,
                                allocator, len, data);
}
void   fanotify_inode_mark_entry__free_unpacked
                     (FanotifyInodeMarkEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_inode_mark_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fanotify_mount_mark_entry__init
                     (FanotifyMountMarkEntry         *message)
{
  static FanotifyMountMarkEntry init_value = FANOTIFY_MOUNT_MARK_ENTRY__INIT;
  *message = init_value;
}
size_t fanotify_mount_mark_entry__get_packed_size
                     (const FanotifyMountMarkEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_mount_mark_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fanotify_mount_mark_entry__pack
                     (const FanotifyMountMarkEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_mount_mark_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fanotify_mount_mark_entry__pack_to_buffer
                     (const FanotifyMountMarkEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_mount_mark_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FanotifyMountMarkEntry *
       fanotify_mount_mark_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FanotifyMountMarkEntry *)
     protobuf_c_message_unpack (&fanotify_mount_mark_entry__descriptor,
                                allocator, len, data);
}
void   fanotify_mount_mark_entry__free_unpacked
                     (FanotifyMountMarkEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_mount_mark_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fanotify_mark_entry__init
                     (FanotifyMarkEntry         *message)
{
  static FanotifyMarkEntry init_value = FANOTIFY_MARK_ENTRY__INIT;
  *message = init_value;
}
size_t fanotify_mark_entry__get_packed_size
                     (const FanotifyMarkEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_mark_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fanotify_mark_entry__pack
                     (const FanotifyMarkEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_mark_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fanotify_mark_entry__pack_to_buffer
                     (const FanotifyMarkEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_mark_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FanotifyMarkEntry *
       fanotify_mark_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FanotifyMarkEntry *)
     protobuf_c_message_unpack (&fanotify_mark_entry__descriptor,
                                allocator, len, data);
}
void   fanotify_mark_entry__free_unpacked
                     (FanotifyMarkEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_mark_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   fanotify_file_entry__init
                     (FanotifyFileEntry         *message)
{
  static FanotifyFileEntry init_value = FANOTIFY_FILE_ENTRY__INIT;
  *message = init_value;
}
size_t fanotify_file_entry__get_packed_size
                     (const FanotifyFileEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_file_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t fanotify_file_entry__pack
                     (const FanotifyFileEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_file_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t fanotify_file_entry__pack_to_buffer
                     (const FanotifyFileEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_file_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
FanotifyFileEntry *
       fanotify_file_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (FanotifyFileEntry *)
     protobuf_c_message_unpack (&fanotify_file_entry__descriptor,
                                allocator, len, data);
}
void   fanotify_file_entry__free_unpacked
                     (FanotifyFileEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &fanotify_file_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor inotify_wd_entry__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InotifyWdEntry, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "i_ino",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InotifyWdEntry, i_ino),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mask",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InotifyWdEntry, mask),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ignored_mask",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InotifyWdEntry, ignored_mask),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_dev",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InotifyWdEntry, s_dev),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wd",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InotifyWdEntry, wd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "f_handle",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InotifyWdEntry, f_handle),
    &fh_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned inotify_wd_entry__field_indices_by_name[] = {
  6,   /* field[6] = f_handle */
  1,   /* field[1] = i_ino */
  0,   /* field[0] = id */
  3,   /* field[3] = ignored_mask */
  2,   /* field[2] = mask */
  4,   /* field[4] = s_dev */
  5,   /* field[5] = wd */
};
static const ProtobufCIntRange inotify_wd_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor inotify_wd_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "inotify_wd_entry",
  "InotifyWdEntry",
  "InotifyWdEntry",
  "",
  sizeof(InotifyWdEntry),
  7,
  inotify_wd_entry__field_descriptors,
  inotify_wd_entry__field_indices_by_name,
  1,  inotify_wd_entry__number_ranges,
  (ProtobufCMessageInit) inotify_wd_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor inotify_file_entry__field_descriptors[4] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InotifyFileEntry, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InotifyFileEntry, flags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fown",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InotifyFileEntry, fown),
    &fown_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wd",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(InotifyFileEntry, n_wd),
    PROTOBUF_C_OFFSETOF(InotifyFileEntry, wd),
    &inotify_wd_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned inotify_file_entry__field_indices_by_name[] = {
  1,   /* field[1] = flags */
  2,   /* field[2] = fown */
  0,   /* field[0] = id */
  3,   /* field[3] = wd */
};
static const ProtobufCIntRange inotify_file_entry__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor inotify_file_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "inotify_file_entry",
  "InotifyFileEntry",
  "InotifyFileEntry",
  "",
  sizeof(InotifyFileEntry),
  4,
  inotify_file_entry__field_descriptors,
  inotify_file_entry__field_indices_by_name,
  2,  inotify_file_entry__number_ranges,
  (ProtobufCMessageInit) inotify_file_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fanotify_inode_mark_entry__field_descriptors[2] =
{
  {
    "i_ino",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyInodeMarkEntry, i_ino),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "f_handle",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyInodeMarkEntry, f_handle),
    &fh_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fanotify_inode_mark_entry__field_indices_by_name[] = {
  1,   /* field[1] = f_handle */
  0,   /* field[0] = i_ino */
};
static const ProtobufCIntRange fanotify_inode_mark_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor fanotify_inode_mark_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "fanotify_inode_mark_entry",
  "FanotifyInodeMarkEntry",
  "FanotifyInodeMarkEntry",
  "",
  sizeof(FanotifyInodeMarkEntry),
  2,
  fanotify_inode_mark_entry__field_descriptors,
  fanotify_inode_mark_entry__field_indices_by_name,
  1,  fanotify_inode_mark_entry__number_ranges,
  (ProtobufCMessageInit) fanotify_inode_mark_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fanotify_mount_mark_entry__field_descriptors[1] =
{
  {
    "mnt_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyMountMarkEntry, mnt_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fanotify_mount_mark_entry__field_indices_by_name[] = {
  0,   /* field[0] = mnt_id */
};
static const ProtobufCIntRange fanotify_mount_mark_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor fanotify_mount_mark_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "fanotify_mount_mark_entry",
  "FanotifyMountMarkEntry",
  "FanotifyMountMarkEntry",
  "",
  sizeof(FanotifyMountMarkEntry),
  1,
  fanotify_mount_mark_entry__field_descriptors,
  fanotify_mount_mark_entry__field_indices_by_name,
  1,  fanotify_mount_mark_entry__number_ranges,
  (ProtobufCMessageInit) fanotify_mount_mark_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fanotify_mark_entry__field_descriptors[8] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyMarkEntry, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyMarkEntry, type),
    &mark_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mflags",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyMarkEntry, mflags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mask",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyMarkEntry, mask),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ignored_mask",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyMarkEntry, ignored_mask),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "s_dev",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyMarkEntry, s_dev),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ie",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyMarkEntry, ie),
    &fanotify_inode_mark_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "me",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyMarkEntry, me),
    &fanotify_mount_mark_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fanotify_mark_entry__field_indices_by_name[] = {
  0,   /* field[0] = id */
  6,   /* field[6] = ie */
  4,   /* field[4] = ignored_mask */
  3,   /* field[3] = mask */
  7,   /* field[7] = me */
  2,   /* field[2] = mflags */
  5,   /* field[5] = s_dev */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange fanotify_mark_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor fanotify_mark_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "fanotify_mark_entry",
  "FanotifyMarkEntry",
  "FanotifyMarkEntry",
  "",
  sizeof(FanotifyMarkEntry),
  8,
  fanotify_mark_entry__field_descriptors,
  fanotify_mark_entry__field_indices_by_name,
  1,  fanotify_mark_entry__number_ranges,
  (ProtobufCMessageInit) fanotify_mark_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor fanotify_file_entry__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyFileEntry, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyFileEntry, flags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fown",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyFileEntry, fown),
    &fown_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "faflags",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyFileEntry, faflags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "evflags",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(FanotifyFileEntry, evflags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mark",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(FanotifyFileEntry, n_mark),
    PROTOBUF_C_OFFSETOF(FanotifyFileEntry, mark),
    &fanotify_mark_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned fanotify_file_entry__field_indices_by_name[] = {
  4,   /* field[4] = evflags */
  3,   /* field[3] = faflags */
  1,   /* field[1] = flags */
  2,   /* field[2] = fown */
  0,   /* field[0] = id */
  5,   /* field[5] = mark */
};
static const ProtobufCIntRange fanotify_file_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor fanotify_file_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "fanotify_file_entry",
  "FanotifyFileEntry",
  "FanotifyFileEntry",
  "",
  sizeof(FanotifyFileEntry),
  6,
  fanotify_file_entry__field_descriptors,
  fanotify_file_entry__field_indices_by_name,
  1,  fanotify_file_entry__number_ranges,
  (ProtobufCMessageInit) fanotify_file_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue mark_type__enum_values_by_number[2] =
{
  { "INODE", "MARK_TYPE__INODE", 1 },
  { "MOUNT", "MARK_TYPE__MOUNT", 2 },
};
static const ProtobufCIntRange mark_type__value_ranges[] = {
{1, 0},{0, 2}
};
const ProtobufCEnumValueIndex mark_type__enum_values_by_name[2] =
{
  { "INODE", 0 },
  { "MOUNT", 1 },
};
const ProtobufCEnumDescriptor mark_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "mark_type",
  "mark_type",
  "MarkType",
  "",
  2,
  mark_type__enum_values_by_number,
  2,
  mark_type__enum_values_by_name,
  1,
  mark_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
