/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "ghost-file.pb-c.h"
void   ghost_file_entry__init
                     (GhostFileEntry         *message)
{
  static GhostFileEntry init_value = GHOST_FILE_ENTRY__INIT;
  *message = init_value;
}
size_t ghost_file_entry__get_packed_size
                     (const GhostFileEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ghost_file_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ghost_file_entry__pack
                     (const GhostFileEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ghost_file_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ghost_file_entry__pack_to_buffer
                     (const GhostFileEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ghost_file_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GhostFileEntry *
       ghost_file_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GhostFileEntry *)
     protobuf_c_message_unpack (&ghost_file_entry__descriptor,
                                allocator, len, data);
}
void   ghost_file_entry__free_unpacked
                     (GhostFileEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ghost_file_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ghost_file_entry__field_descriptors[8] =
{
  {
    "uid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GhostFileEntry, uid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GhostFileEntry, gid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GhostFileEntry, mode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dev",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(GhostFileEntry, has_dev),
    PROTOBUF_C_OFFSETOF(GhostFileEntry, dev),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ino",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    PROTOBUF_C_OFFSETOF(GhostFileEntry, has_ino),
    PROTOBUF_C_OFFSETOF(GhostFileEntry, ino),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rdev",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(GhostFileEntry, has_rdev),
    PROTOBUF_C_OFFSETOF(GhostFileEntry, rdev),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "atim",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GhostFileEntry, atim),
    &timeval__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtim",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(GhostFileEntry, mtim),
    &timeval__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ghost_file_entry__field_indices_by_name[] = {
  6,   /* field[6] = atim */
  3,   /* field[3] = dev */
  1,   /* field[1] = gid */
  4,   /* field[4] = ino */
  2,   /* field[2] = mode */
  7,   /* field[7] = mtim */
  5,   /* field[5] = rdev */
  0,   /* field[0] = uid */
};
static const ProtobufCIntRange ghost_file_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor ghost_file_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ghost_file_entry",
  "GhostFileEntry",
  "GhostFileEntry",
  "",
  sizeof(GhostFileEntry),
  8,
  ghost_file_entry__field_descriptors,
  ghost_file_entry__field_indices_by_name,
  1,  ghost_file_entry__number_ranges,
  (ProtobufCMessageInit) ghost_file_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
