/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "inventory.pb-c.h"
void   inventory_entry__init
                     (InventoryEntry         *message)
{
  static InventoryEntry init_value = INVENTORY_ENTRY__INIT;
  *message = init_value;
}
size_t inventory_entry__get_packed_size
                     (const InventoryEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inventory_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t inventory_entry__pack
                     (const InventoryEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inventory_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t inventory_entry__pack_to_buffer
                     (const InventoryEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inventory_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InventoryEntry *
       inventory_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InventoryEntry *)
     protobuf_c_message_unpack (&inventory_entry__descriptor,
                                allocator, len, data);
}
void   inventory_entry__free_unpacked
                     (InventoryEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inventory_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor inventory_entry__field_descriptors[6] =
{
  {
    "img_version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InventoryEntry, img_version),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fdinfo_per_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(InventoryEntry, has_fdinfo_per_id),
    PROTOBUF_C_OFFSETOF(InventoryEntry, fdinfo_per_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "root_ids",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InventoryEntry, root_ids),
    &task_kobj_ids_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ns_per_id",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(InventoryEntry, has_ns_per_id),
    PROTOBUF_C_OFFSETOF(InventoryEntry, ns_per_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "root_cg_set",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(InventoryEntry, has_root_cg_set),
    PROTOBUF_C_OFFSETOF(InventoryEntry, root_cg_set),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lsmtype",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(InventoryEntry, has_lsmtype),
    PROTOBUF_C_OFFSETOF(InventoryEntry, lsmtype),
    &lsmtype__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned inventory_entry__field_indices_by_name[] = {
  1,   /* field[1] = fdinfo_per_id */
  0,   /* field[0] = img_version */
  5,   /* field[5] = lsmtype */
  3,   /* field[3] = ns_per_id */
  4,   /* field[4] = root_cg_set */
  2,   /* field[2] = root_ids */
};
static const ProtobufCIntRange inventory_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor inventory_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "inventory_entry",
  "InventoryEntry",
  "InventoryEntry",
  "",
  sizeof(InventoryEntry),
  6,
  inventory_entry__field_descriptors,
  inventory_entry__field_indices_by_name,
  1,  inventory_entry__number_ranges,
  (ProtobufCMessageInit) inventory_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue lsmtype__enum_values_by_number[3] =
{
  { "NO_LSM", "LSMTYPE__NO_LSM", 0 },
  { "SELINUX", "LSMTYPE__SELINUX", 1 },
  { "APPARMOR", "LSMTYPE__APPARMOR", 2 },
};
static const ProtobufCIntRange lsmtype__value_ranges[] = {
{0, 0},{0, 3}
};
const ProtobufCEnumValueIndex lsmtype__enum_values_by_name[3] =
{
  { "APPARMOR", 2 },
  { "NO_LSM", 0 },
  { "SELINUX", 1 },
};
const ProtobufCEnumDescriptor lsmtype__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "lsmtype",
  "lsmtype",
  "Lsmtype",
  "",
  3,
  lsmtype__enum_values_by_number,
  3,
  lsmtype__enum_values_by_name,
  1,
  lsmtype__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
