/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "ipc-var.pb-c.h"
void   ipc_var_entry__init
                     (IpcVarEntry         *message)
{
  static IpcVarEntry init_value = IPC_VAR_ENTRY__INIT;
  *message = init_value;
}
size_t ipc_var_entry__get_packed_size
                     (const IpcVarEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ipc_var_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc_var_entry__pack
                     (const IpcVarEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ipc_var_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc_var_entry__pack_to_buffer
                     (const IpcVarEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ipc_var_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IpcVarEntry *
       ipc_var_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IpcVarEntry *)
     protobuf_c_message_unpack (&ipc_var_entry__descriptor,
                                allocator, len, data);
}
void   ipc_var_entry__free_unpacked
                     (IpcVarEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ipc_var_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ipc_var_entry__field_descriptors[14] =
{
  {
    "sem_ctls",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(IpcVarEntry, n_sem_ctls),
    PROTOBUF_C_OFFSETOF(IpcVarEntry, sem_ctls),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_ctlmax",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IpcVarEntry, msg_ctlmax),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_ctlmnb",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IpcVarEntry, msg_ctlmnb),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "msg_ctlmni",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IpcVarEntry, msg_ctlmni),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auto_msgmni",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IpcVarEntry, auto_msgmni),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shm_ctlmax",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IpcVarEntry, shm_ctlmax),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shm_ctlall",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IpcVarEntry, shm_ctlall),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shm_ctlmni",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IpcVarEntry, shm_ctlmni),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shm_rmid_forced",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IpcVarEntry, shm_rmid_forced),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mq_queues_max",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IpcVarEntry, mq_queues_max),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mq_msg_max",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IpcVarEntry, mq_msg_max),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mq_msgsize_max",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(IpcVarEntry, mq_msgsize_max),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mq_msg_default",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(IpcVarEntry, has_mq_msg_default),
    PROTOBUF_C_OFFSETOF(IpcVarEntry, mq_msg_default),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mq_msgsize_default",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(IpcVarEntry, has_mq_msgsize_default),
    PROTOBUF_C_OFFSETOF(IpcVarEntry, mq_msgsize_default),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc_var_entry__field_indices_by_name[] = {
  4,   /* field[4] = auto_msgmni */
  12,   /* field[12] = mq_msg_default */
  10,   /* field[10] = mq_msg_max */
  13,   /* field[13] = mq_msgsize_default */
  11,   /* field[11] = mq_msgsize_max */
  9,   /* field[9] = mq_queues_max */
  1,   /* field[1] = msg_ctlmax */
  2,   /* field[2] = msg_ctlmnb */
  3,   /* field[3] = msg_ctlmni */
  0,   /* field[0] = sem_ctls */
  6,   /* field[6] = shm_ctlall */
  5,   /* field[5] = shm_ctlmax */
  7,   /* field[7] = shm_ctlmni */
  8,   /* field[8] = shm_rmid_forced */
};
static const ProtobufCIntRange ipc_var_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 14 }
};
const ProtobufCMessageDescriptor ipc_var_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ipc_var_entry",
  "IpcVarEntry",
  "IpcVarEntry",
  "",
  sizeof(IpcVarEntry),
  14,
  ipc_var_entry__field_descriptors,
  ipc_var_entry__field_indices_by_name,
  1,  ipc_var_entry__number_ranges,
  (ProtobufCMessageInit) ipc_var_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
