/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_ipc_2dshm_2eproto__INCLUDED
#define PROTOBUF_C_ipc_2dshm_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "ipc-desc.pb-c.h"

typedef struct _IpcShmEntry IpcShmEntry;


/* --- enums --- */


/* --- messages --- */

struct  _IpcShmEntry
{
  ProtobufCMessage base;
  IpcDescEntry *desc;
  uint64_t size;
};
#define IPC_SHM_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&ipc_shm_entry__descriptor) \
    , NULL, 0 }


/* IpcShmEntry methods */
void   ipc_shm_entry__init
                     (IpcShmEntry         *message);
size_t ipc_shm_entry__get_packed_size
                     (const IpcShmEntry   *message);
size_t ipc_shm_entry__pack
                     (const IpcShmEntry   *message,
                      uint8_t             *out);
size_t ipc_shm_entry__pack_to_buffer
                     (const IpcShmEntry   *message,
                      ProtobufCBuffer     *buffer);
IpcShmEntry *
       ipc_shm_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   ipc_shm_entry__free_unpacked
                     (IpcShmEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*IpcShmEntry_Closure)
                 (const IpcShmEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor ipc_shm_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_ipc_2dshm_2eproto__INCLUDED */
