/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "netdev.pb-c.h"
void   net_device_entry__init
                     (NetDeviceEntry         *message)
{
  static NetDeviceEntry init_value = NET_DEVICE_ENTRY__INIT;
  *message = init_value;
}
size_t net_device_entry__get_packed_size
                     (const NetDeviceEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &net_device_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t net_device_entry__pack
                     (const NetDeviceEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &net_device_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t net_device_entry__pack_to_buffer
                     (const NetDeviceEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &net_device_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetDeviceEntry *
       net_device_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetDeviceEntry *)
     protobuf_c_message_unpack (&net_device_entry__descriptor,
                                allocator, len, data);
}
void   net_device_entry__free_unpacked
                     (NetDeviceEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &net_device_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   netns_entry__init
                     (NetnsEntry         *message)
{
  static NetnsEntry init_value = NETNS_ENTRY__INIT;
  *message = init_value;
}
size_t netns_entry__get_packed_size
                     (const NetnsEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &netns_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t netns_entry__pack
                     (const NetnsEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &netns_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t netns_entry__pack_to_buffer
                     (const NetnsEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &netns_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NetnsEntry *
       netns_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NetnsEntry *)
     protobuf_c_message_unpack (&netns_entry__descriptor,
                                allocator, len, data);
}
void   netns_entry__free_unpacked
                     (NetnsEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &netns_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor net_device_entry__field_descriptors[10] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, type),
    &nd_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ifindex",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, ifindex),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mtu",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, mtu),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, flags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tun",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, tun),
    &tun_link_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, has_address),
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, address),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, n_conf),
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, conf),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf4",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, n_conf4),
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, conf4),
    &sysctl_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conf6",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, n_conf6),
    PROTOBUF_C_OFFSETOF(NetDeviceEntry, conf6),
    &sysctl_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned net_device_entry__field_indices_by_name[] = {
  6,   /* field[6] = address */
  7,   /* field[7] = conf */
  8,   /* field[8] = conf4 */
  9,   /* field[9] = conf6 */
  3,   /* field[3] = flags */
  1,   /* field[1] = ifindex */
  2,   /* field[2] = mtu */
  4,   /* field[4] = name */
  5,   /* field[5] = tun */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange net_device_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor net_device_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "net_device_entry",
  "NetDeviceEntry",
  "NetDeviceEntry",
  "",
  sizeof(NetDeviceEntry),
  10,
  net_device_entry__field_descriptors,
  net_device_entry__field_indices_by_name,
  1,  net_device_entry__number_ranges,
  (ProtobufCMessageInit) net_device_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor netns_entry__field_descriptors[6] =
{
  {
    "def_conf",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(NetnsEntry, n_def_conf),
    PROTOBUF_C_OFFSETOF(NetnsEntry, def_conf),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all_conf",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(NetnsEntry, n_all_conf),
    PROTOBUF_C_OFFSETOF(NetnsEntry, all_conf),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "def_conf4",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(NetnsEntry, n_def_conf4),
    PROTOBUF_C_OFFSETOF(NetnsEntry, def_conf4),
    &sysctl_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all_conf4",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(NetnsEntry, n_all_conf4),
    PROTOBUF_C_OFFSETOF(NetnsEntry, all_conf4),
    &sysctl_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "def_conf6",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(NetnsEntry, n_def_conf6),
    PROTOBUF_C_OFFSETOF(NetnsEntry, def_conf6),
    &sysctl_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "all_conf6",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(NetnsEntry, n_all_conf6),
    PROTOBUF_C_OFFSETOF(NetnsEntry, all_conf6),
    &sysctl_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned netns_entry__field_indices_by_name[] = {
  1,   /* field[1] = all_conf */
  3,   /* field[3] = all_conf4 */
  5,   /* field[5] = all_conf6 */
  0,   /* field[0] = def_conf */
  2,   /* field[2] = def_conf4 */
  4,   /* field[4] = def_conf6 */
};
static const ProtobufCIntRange netns_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor netns_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "netns_entry",
  "NetnsEntry",
  "NetnsEntry",
  "",
  sizeof(NetnsEntry),
  6,
  netns_entry__field_descriptors,
  netns_entry__field_indices_by_name,
  1,  netns_entry__number_ranges,
  (ProtobufCMessageInit) netns_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue nd_type__enum_values_by_number[6] =
{
  { "LOOPBACK", "ND_TYPE__LOOPBACK", 1 },
  { "VETH", "ND_TYPE__VETH", 2 },
  { "TUN", "ND_TYPE__TUN", 3 },
  { "EXTLINK", "ND_TYPE__EXTLINK", 4 },
  { "VENET", "ND_TYPE__VENET", 5 },
  { "BRIDGE", "ND_TYPE__BRIDGE", 6 },
};
static const ProtobufCIntRange nd_type__value_ranges[] = {
{1, 0},{0, 6}
};
const ProtobufCEnumValueIndex nd_type__enum_values_by_name[6] =
{
  { "BRIDGE", 5 },
  { "EXTLINK", 3 },
  { "LOOPBACK", 0 },
  { "TUN", 2 },
  { "VENET", 4 },
  { "VETH", 1 },
};
const ProtobufCEnumDescriptor nd_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "nd_type",
  "nd_type",
  "NdType",
  "",
  6,
  nd_type__enum_values_by_number,
  6,
  nd_type__enum_values_by_name,
  1,
  nd_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
