/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_remap_2dfile_2dpath_2eproto__INCLUDED
#define PROTOBUF_C_remap_2dfile_2dpath_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _RemapFilePathEntry RemapFilePathEntry;


/* --- enums --- */

typedef enum _RemapType {
  REMAP_TYPE__LINKED = 0,
  REMAP_TYPE__GHOST = 1,
  REMAP_TYPE__PROCFS = 2
} RemapType;

/* --- messages --- */

struct  _RemapFilePathEntry
{
  ProtobufCMessage base;
  uint32_t orig_id;
  uint32_t remap_id;
  protobuf_c_boolean has_remap_type;
  RemapType remap_type;
};
#define REMAP_FILE_PATH_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&remap_file_path_entry__descriptor) \
    , 0, 0, 0,0 }


/* RemapFilePathEntry methods */
void   remap_file_path_entry__init
                     (RemapFilePathEntry         *message);
size_t remap_file_path_entry__get_packed_size
                     (const RemapFilePathEntry   *message);
size_t remap_file_path_entry__pack
                     (const RemapFilePathEntry   *message,
                      uint8_t             *out);
size_t remap_file_path_entry__pack_to_buffer
                     (const RemapFilePathEntry   *message,
                      ProtobufCBuffer     *buffer);
RemapFilePathEntry *
       remap_file_path_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   remap_file_path_entry__free_unpacked
                     (RemapFilePathEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RemapFilePathEntry_Closure)
                 (const RemapFilePathEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    remap_type__descriptor;
extern const ProtobufCMessageDescriptor remap_file_path_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_remap_2dfile_2dpath_2eproto__INCLUDED */
