/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "rpc.pb-c.h"
void   criu_page_server_info__init
                     (CriuPageServerInfo         *message)
{
  static CriuPageServerInfo init_value = CRIU_PAGE_SERVER_INFO__INIT;
  *message = init_value;
}
size_t criu_page_server_info__get_packed_size
                     (const CriuPageServerInfo *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_page_server_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t criu_page_server_info__pack
                     (const CriuPageServerInfo *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_page_server_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t criu_page_server_info__pack_to_buffer
                     (const CriuPageServerInfo *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_page_server_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CriuPageServerInfo *
       criu_page_server_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CriuPageServerInfo *)
     protobuf_c_message_unpack (&criu_page_server_info__descriptor,
                                allocator, len, data);
}
void   criu_page_server_info__free_unpacked
                     (CriuPageServerInfo *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_page_server_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   criu_veth_pair__init
                     (CriuVethPair         *message)
{
  static CriuVethPair init_value = CRIU_VETH_PAIR__INIT;
  *message = init_value;
}
size_t criu_veth_pair__get_packed_size
                     (const CriuVethPair *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_veth_pair__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t criu_veth_pair__pack
                     (const CriuVethPair *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_veth_pair__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t criu_veth_pair__pack_to_buffer
                     (const CriuVethPair *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_veth_pair__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CriuVethPair *
       criu_veth_pair__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CriuVethPair *)
     protobuf_c_message_unpack (&criu_veth_pair__descriptor,
                                allocator, len, data);
}
void   criu_veth_pair__free_unpacked
                     (CriuVethPair *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_veth_pair__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ext_mount_map__init
                     (ExtMountMap         *message)
{
  static ExtMountMap init_value = EXT_MOUNT_MAP__INIT;
  *message = init_value;
}
size_t ext_mount_map__get_packed_size
                     (const ExtMountMap *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ext_mount_map__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ext_mount_map__pack
                     (const ExtMountMap *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ext_mount_map__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ext_mount_map__pack_to_buffer
                     (const ExtMountMap *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ext_mount_map__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExtMountMap *
       ext_mount_map__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExtMountMap *)
     protobuf_c_message_unpack (&ext_mount_map__descriptor,
                                allocator, len, data);
}
void   ext_mount_map__free_unpacked
                     (ExtMountMap *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ext_mount_map__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   join_namespace__init
                     (JoinNamespace         *message)
{
  static JoinNamespace init_value = JOIN_NAMESPACE__INIT;
  *message = init_value;
}
size_t join_namespace__get_packed_size
                     (const JoinNamespace *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &join_namespace__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t join_namespace__pack
                     (const JoinNamespace *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &join_namespace__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t join_namespace__pack_to_buffer
                     (const JoinNamespace *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &join_namespace__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
JoinNamespace *
       join_namespace__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (JoinNamespace *)
     protobuf_c_message_unpack (&join_namespace__descriptor,
                                allocator, len, data);
}
void   join_namespace__free_unpacked
                     (JoinNamespace *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &join_namespace__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   inherit_fd__init
                     (InheritFd         *message)
{
  static InheritFd init_value = INHERIT_FD__INIT;
  *message = init_value;
}
size_t inherit_fd__get_packed_size
                     (const InheritFd *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inherit_fd__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t inherit_fd__pack
                     (const InheritFd *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inherit_fd__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t inherit_fd__pack_to_buffer
                     (const InheritFd *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inherit_fd__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InheritFd *
       inherit_fd__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InheritFd *)
     protobuf_c_message_unpack (&inherit_fd__descriptor,
                                allocator, len, data);
}
void   inherit_fd__free_unpacked
                     (InheritFd *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inherit_fd__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cgroup_root__init
                     (CgroupRoot         *message)
{
  static CgroupRoot init_value = CGROUP_ROOT__INIT;
  *message = init_value;
}
size_t cgroup_root__get_packed_size
                     (const CgroupRoot *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cgroup_root__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cgroup_root__pack
                     (const CgroupRoot *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cgroup_root__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cgroup_root__pack_to_buffer
                     (const CgroupRoot *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cgroup_root__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CgroupRoot *
       cgroup_root__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CgroupRoot *)
     protobuf_c_message_unpack (&cgroup_root__descriptor,
                                allocator, len, data);
}
void   cgroup_root__free_unpacked
                     (CgroupRoot *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cgroup_root__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   unix_sk__init
                     (UnixSk         *message)
{
  static UnixSk init_value = UNIX_SK__INIT;
  *message = init_value;
}
size_t unix_sk__get_packed_size
                     (const UnixSk *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unix_sk__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t unix_sk__pack
                     (const UnixSk *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unix_sk__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t unix_sk__pack_to_buffer
                     (const UnixSk *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unix_sk__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UnixSk *
       unix_sk__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UnixSk *)
     protobuf_c_message_unpack (&unix_sk__descriptor,
                                allocator, len, data);
}
void   unix_sk__free_unpacked
                     (UnixSk *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &unix_sk__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   criu_opts__init
                     (CriuOpts         *message)
{
  static CriuOpts init_value = CRIU_OPTS__INIT;
  *message = init_value;
}
size_t criu_opts__get_packed_size
                     (const CriuOpts *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_opts__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t criu_opts__pack
                     (const CriuOpts *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_opts__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t criu_opts__pack_to_buffer
                     (const CriuOpts *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_opts__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CriuOpts *
       criu_opts__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CriuOpts *)
     protobuf_c_message_unpack (&criu_opts__descriptor,
                                allocator, len, data);
}
void   criu_opts__free_unpacked
                     (CriuOpts *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_opts__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   criu_dump_resp__init
                     (CriuDumpResp         *message)
{
  static CriuDumpResp init_value = CRIU_DUMP_RESP__INIT;
  *message = init_value;
}
size_t criu_dump_resp__get_packed_size
                     (const CriuDumpResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_dump_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t criu_dump_resp__pack
                     (const CriuDumpResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_dump_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t criu_dump_resp__pack_to_buffer
                     (const CriuDumpResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_dump_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CriuDumpResp *
       criu_dump_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CriuDumpResp *)
     protobuf_c_message_unpack (&criu_dump_resp__descriptor,
                                allocator, len, data);
}
void   criu_dump_resp__free_unpacked
                     (CriuDumpResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_dump_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   criu_restore_resp__init
                     (CriuRestoreResp         *message)
{
  static CriuRestoreResp init_value = CRIU_RESTORE_RESP__INIT;
  *message = init_value;
}
size_t criu_restore_resp__get_packed_size
                     (const CriuRestoreResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_restore_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t criu_restore_resp__pack
                     (const CriuRestoreResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_restore_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t criu_restore_resp__pack_to_buffer
                     (const CriuRestoreResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_restore_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CriuRestoreResp *
       criu_restore_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CriuRestoreResp *)
     protobuf_c_message_unpack (&criu_restore_resp__descriptor,
                                allocator, len, data);
}
void   criu_restore_resp__free_unpacked
                     (CriuRestoreResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_restore_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   criu_notify__init
                     (CriuNotify         *message)
{
  static CriuNotify init_value = CRIU_NOTIFY__INIT;
  *message = init_value;
}
size_t criu_notify__get_packed_size
                     (const CriuNotify *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_notify__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t criu_notify__pack
                     (const CriuNotify *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_notify__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t criu_notify__pack_to_buffer
                     (const CriuNotify *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_notify__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CriuNotify *
       criu_notify__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CriuNotify *)
     protobuf_c_message_unpack (&criu_notify__descriptor,
                                allocator, len, data);
}
void   criu_notify__free_unpacked
                     (CriuNotify *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_notify__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   criu_features__init
                     (CriuFeatures         *message)
{
  static CriuFeatures init_value = CRIU_FEATURES__INIT;
  *message = init_value;
}
size_t criu_features__get_packed_size
                     (const CriuFeatures *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_features__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t criu_features__pack
                     (const CriuFeatures *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_features__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t criu_features__pack_to_buffer
                     (const CriuFeatures *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_features__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CriuFeatures *
       criu_features__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CriuFeatures *)
     protobuf_c_message_unpack (&criu_features__descriptor,
                                allocator, len, data);
}
void   criu_features__free_unpacked
                     (CriuFeatures *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_features__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   criu_req__init
                     (CriuReq         *message)
{
  static CriuReq init_value = CRIU_REQ__INIT;
  *message = init_value;
}
size_t criu_req__get_packed_size
                     (const CriuReq *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t criu_req__pack
                     (const CriuReq *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t criu_req__pack_to_buffer
                     (const CriuReq *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CriuReq *
       criu_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CriuReq *)
     protobuf_c_message_unpack (&criu_req__descriptor,
                                allocator, len, data);
}
void   criu_req__free_unpacked
                     (CriuReq *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   criu_resp__init
                     (CriuResp         *message)
{
  static CriuResp init_value = CRIU_RESP__INIT;
  *message = init_value;
}
size_t criu_resp__get_packed_size
                     (const CriuResp *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_resp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t criu_resp__pack
                     (const CriuResp *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_resp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t criu_resp__pack_to_buffer
                     (const CriuResp *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_resp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CriuResp *
       criu_resp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CriuResp *)
     protobuf_c_message_unpack (&criu_resp__descriptor,
                                allocator, len, data);
}
void   criu_resp__free_unpacked
                     (CriuResp *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &criu_resp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor criu_page_server_info__field_descriptors[4] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuPageServerInfo, address),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CriuPageServerInfo, has_port),
    PROTOBUF_C_OFFSETOF(CriuPageServerInfo, port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CriuPageServerInfo, has_pid),
    PROTOBUF_C_OFFSETOF(CriuPageServerInfo, pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fd",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CriuPageServerInfo, has_fd),
    PROTOBUF_C_OFFSETOF(CriuPageServerInfo, fd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned criu_page_server_info__field_indices_by_name[] = {
  0,   /* field[0] = address */
  3,   /* field[3] = fd */
  2,   /* field[2] = pid */
  1,   /* field[1] = port */
};
static const ProtobufCIntRange criu_page_server_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor criu_page_server_info__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "criu_page_server_info",
  "CriuPageServerInfo",
  "CriuPageServerInfo",
  "",
  sizeof(CriuPageServerInfo),
  4,
  criu_page_server_info__field_descriptors,
  criu_page_server_info__field_indices_by_name,
  1,  criu_page_server_info__number_ranges,
  (ProtobufCMessageInit) criu_page_server_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor criu_veth_pair__field_descriptors[2] =
{
  {
    "if_in",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuVethPair, if_in),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "if_out",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuVethPair, if_out),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned criu_veth_pair__field_indices_by_name[] = {
  0,   /* field[0] = if_in */
  1,   /* field[1] = if_out */
};
static const ProtobufCIntRange criu_veth_pair__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor criu_veth_pair__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "criu_veth_pair",
  "CriuVethPair",
  "CriuVethPair",
  "",
  sizeof(CriuVethPair),
  2,
  criu_veth_pair__field_descriptors,
  criu_veth_pair__field_indices_by_name,
  1,  criu_veth_pair__number_ranges,
  (ProtobufCMessageInit) criu_veth_pair__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ext_mount_map__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ExtMountMap, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "val",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(ExtMountMap, val),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ext_mount_map__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = val */
};
static const ProtobufCIntRange ext_mount_map__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ext_mount_map__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ext_mount_map",
  "ExtMountMap",
  "ExtMountMap",
  "",
  sizeof(ExtMountMap),
  2,
  ext_mount_map__field_descriptors,
  ext_mount_map__field_indices_by_name,
  1,  ext_mount_map__number_ranges,
  (ProtobufCMessageInit) ext_mount_map__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor join_namespace__field_descriptors[3] =
{
  {
    "ns",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(JoinNamespace, ns),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ns_file",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(JoinNamespace, ns_file),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extra_opt",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(JoinNamespace, extra_opt),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned join_namespace__field_indices_by_name[] = {
  2,   /* field[2] = extra_opt */
  0,   /* field[0] = ns */
  1,   /* field[1] = ns_file */
};
static const ProtobufCIntRange join_namespace__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor join_namespace__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "join_namespace",
  "JoinNamespace",
  "JoinNamespace",
  "",
  sizeof(JoinNamespace),
  3,
  join_namespace__field_descriptors,
  join_namespace__field_indices_by_name,
  1,  join_namespace__number_ranges,
  (ProtobufCMessageInit) join_namespace__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor inherit_fd__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InheritFd, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fd",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InheritFd, fd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned inherit_fd__field_indices_by_name[] = {
  1,   /* field[1] = fd */
  0,   /* field[0] = key */
};
static const ProtobufCIntRange inherit_fd__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor inherit_fd__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "inherit_fd",
  "InheritFd",
  "InheritFd",
  "",
  sizeof(InheritFd),
  2,
  inherit_fd__field_descriptors,
  inherit_fd__field_indices_by_name,
  1,  inherit_fd__number_ranges,
  (ProtobufCMessageInit) inherit_fd__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cgroup_root__field_descriptors[2] =
{
  {
    "ctrl",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CgroupRoot, ctrl),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "path",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CgroupRoot, path),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cgroup_root__field_indices_by_name[] = {
  0,   /* field[0] = ctrl */
  1,   /* field[1] = path */
};
static const ProtobufCIntRange cgroup_root__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor cgroup_root__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "cgroup_root",
  "CgroupRoot",
  "CgroupRoot",
  "",
  sizeof(CgroupRoot),
  2,
  cgroup_root__field_descriptors,
  cgroup_root__field_indices_by_name,
  1,  cgroup_root__number_ranges,
  (ProtobufCMessageInit) cgroup_root__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor unix_sk__field_descriptors[1] =
{
  {
    "inode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UnixSk, inode),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned unix_sk__field_indices_by_name[] = {
  0,   /* field[0] = inode */
};
static const ProtobufCIntRange unix_sk__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor unix_sk__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "unix_sk",
  "UnixSk",
  "UnixSk",
  "",
  sizeof(UnixSk),
  1,
  unix_sk__field_descriptors,
  unix_sk__field_indices_by_name,
  1,  unix_sk__number_ranges,
  (ProtobufCMessageInit) unix_sk__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t criu_opts__log_level__default_value = 2;
static const uint32_t criu_opts__cpu_cap__default_value = 4294967295;
static const uint32_t criu_opts__ghost_limit__default_value = 1048576;
static const ProtobufCFieldDescriptor criu_opts__field_descriptors[45] =
{
  {
    "images_dir_fd",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuOpts, images_dir_fd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_pid),
    PROTOBUF_C_OFFSETOF(CriuOpts, pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "leave_running",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_leave_running),
    PROTOBUF_C_OFFSETOF(CriuOpts, leave_running),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext_unix_sk",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_ext_unix_sk),
    PROTOBUF_C_OFFSETOF(CriuOpts, ext_unix_sk),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcp_established",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_tcp_established),
    PROTOBUF_C_OFFSETOF(CriuOpts, tcp_established),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "evasive_devices",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_evasive_devices),
    PROTOBUF_C_OFFSETOF(CriuOpts, evasive_devices),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shell_job",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_shell_job),
    PROTOBUF_C_OFFSETOF(CriuOpts, shell_job),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "file_locks",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_file_locks),
    PROTOBUF_C_OFFSETOF(CriuOpts, file_locks),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_level",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_log_level),
    PROTOBUF_C_OFFSETOF(CriuOpts, log_level),
    NULL,
    &criu_opts__log_level__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_file",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuOpts, log_file),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ps",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuOpts, ps),
    &criu_page_server_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notify_scripts",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_notify_scripts),
    PROTOBUF_C_OFFSETOF(CriuOpts, notify_scripts),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "root",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuOpts, root),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_img",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuOpts, parent_img),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "track_mem",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_track_mem),
    PROTOBUF_C_OFFSETOF(CriuOpts, track_mem),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auto_dedup",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_auto_dedup),
    PROTOBUF_C_OFFSETOF(CriuOpts, auto_dedup),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "work_dir_fd",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_work_dir_fd),
    PROTOBUF_C_OFFSETOF(CriuOpts, work_dir_fd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "link_remap",
    18,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_link_remap),
    PROTOBUF_C_OFFSETOF(CriuOpts, link_remap),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "veths",
    19,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_veths),
    PROTOBUF_C_OFFSETOF(CriuOpts, veths),
    &criu_veth_pair__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cpu_cap",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_cpu_cap),
    PROTOBUF_C_OFFSETOF(CriuOpts, cpu_cap),
    NULL,
    &criu_opts__cpu_cap__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "force_irmap",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_force_irmap),
    PROTOBUF_C_OFFSETOF(CriuOpts, force_irmap),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exec_cmd",
    22,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_exec_cmd),
    PROTOBUF_C_OFFSETOF(CriuOpts, exec_cmd),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext_mnt",
    23,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_ext_mnt),
    PROTOBUF_C_OFFSETOF(CriuOpts, ext_mnt),
    &ext_mount_map__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "manage_cgroups",
    24,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_manage_cgroups),
    PROTOBUF_C_OFFSETOF(CriuOpts, manage_cgroups),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cg_root",
    25,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_cg_root),
    PROTOBUF_C_OFFSETOF(CriuOpts, cg_root),
    &cgroup_root__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rst_sibling",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_rst_sibling),
    PROTOBUF_C_OFFSETOF(CriuOpts, rst_sibling),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inherit_fd",
    27,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_inherit_fd),
    PROTOBUF_C_OFFSETOF(CriuOpts, inherit_fd),
    &inherit_fd__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "auto_ext_mnt",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_auto_ext_mnt),
    PROTOBUF_C_OFFSETOF(CriuOpts, auto_ext_mnt),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext_sharing",
    29,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_ext_sharing),
    PROTOBUF_C_OFFSETOF(CriuOpts, ext_sharing),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ext_masters",
    30,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_ext_masters),
    PROTOBUF_C_OFFSETOF(CriuOpts, ext_masters),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "skip_mnt",
    31,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_skip_mnt),
    PROTOBUF_C_OFFSETOF(CriuOpts, skip_mnt),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable_fs",
    32,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_enable_fs),
    PROTOBUF_C_OFFSETOF(CriuOpts, enable_fs),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unix_sk_ino",
    33,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_unix_sk_ino),
    PROTOBUF_C_OFFSETOF(CriuOpts, unix_sk_ino),
    &unix_sk__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "manage_cgroups_mode",
    34,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_manage_cgroups_mode),
    PROTOBUF_C_OFFSETOF(CriuOpts, manage_cgroups_mode),
    &criu_cg_mode__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ghost_limit",
    35,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_ghost_limit),
    PROTOBUF_C_OFFSETOF(CriuOpts, ghost_limit),
    NULL,
    &criu_opts__ghost_limit__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "irmap_scan_paths",
    36,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_irmap_scan_paths),
    PROTOBUF_C_OFFSETOF(CriuOpts, irmap_scan_paths),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "external",
    37,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_external),
    PROTOBUF_C_OFFSETOF(CriuOpts, external),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "empty_ns",
    38,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_empty_ns),
    PROTOBUF_C_OFFSETOF(CriuOpts, empty_ns),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "join_ns",
    39,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_join_ns),
    PROTOBUF_C_OFFSETOF(CriuOpts, join_ns),
    &join_namespace__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cgroup_props",
    41,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuOpts, cgroup_props),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cgroup_props_file",
    42,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuOpts, cgroup_props_file),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cgroup_dump_controller",
    43,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(CriuOpts, n_cgroup_dump_controller),
    PROTOBUF_C_OFFSETOF(CriuOpts, cgroup_dump_controller),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "freeze_cgroup",
    44,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuOpts, freeze_cgroup),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timeout",
    45,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_timeout),
    PROTOBUF_C_OFFSETOF(CriuOpts, timeout),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tcp_skip_in_flight",
    46,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuOpts, has_tcp_skip_in_flight),
    PROTOBUF_C_OFFSETOF(CriuOpts, tcp_skip_in_flight),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned criu_opts__field_indices_by_name[] = {
  15,   /* field[15] = auto_dedup */
  27,   /* field[27] = auto_ext_mnt */
  24,   /* field[24] = cg_root */
  41,   /* field[41] = cgroup_dump_controller */
  39,   /* field[39] = cgroup_props */
  40,   /* field[40] = cgroup_props_file */
  19,   /* field[19] = cpu_cap */
  37,   /* field[37] = empty_ns */
  31,   /* field[31] = enable_fs */
  5,   /* field[5] = evasive_devices */
  21,   /* field[21] = exec_cmd */
  29,   /* field[29] = ext_masters */
  22,   /* field[22] = ext_mnt */
  28,   /* field[28] = ext_sharing */
  3,   /* field[3] = ext_unix_sk */
  36,   /* field[36] = external */
  7,   /* field[7] = file_locks */
  20,   /* field[20] = force_irmap */
  42,   /* field[42] = freeze_cgroup */
  34,   /* field[34] = ghost_limit */
  0,   /* field[0] = images_dir_fd */
  26,   /* field[26] = inherit_fd */
  35,   /* field[35] = irmap_scan_paths */
  38,   /* field[38] = join_ns */
  2,   /* field[2] = leave_running */
  17,   /* field[17] = link_remap */
  9,   /* field[9] = log_file */
  8,   /* field[8] = log_level */
  23,   /* field[23] = manage_cgroups */
  33,   /* field[33] = manage_cgroups_mode */
  11,   /* field[11] = notify_scripts */
  13,   /* field[13] = parent_img */
  1,   /* field[1] = pid */
  10,   /* field[10] = ps */
  12,   /* field[12] = root */
  25,   /* field[25] = rst_sibling */
  6,   /* field[6] = shell_job */
  30,   /* field[30] = skip_mnt */
  4,   /* field[4] = tcp_established */
  44,   /* field[44] = tcp_skip_in_flight */
  43,   /* field[43] = timeout */
  14,   /* field[14] = track_mem */
  32,   /* field[32] = unix_sk_ino */
  18,   /* field[18] = veths */
  16,   /* field[16] = work_dir_fd */
};
static const ProtobufCIntRange criu_opts__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 41, 39 },
  { 0, 45 }
};
const ProtobufCMessageDescriptor criu_opts__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "criu_opts",
  "CriuOpts",
  "CriuOpts",
  "",
  sizeof(CriuOpts),
  45,
  criu_opts__field_descriptors,
  criu_opts__field_indices_by_name,
  2,  criu_opts__number_ranges,
  (ProtobufCMessageInit) criu_opts__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor criu_dump_resp__field_descriptors[1] =
{
  {
    "restored",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuDumpResp, has_restored),
    PROTOBUF_C_OFFSETOF(CriuDumpResp, restored),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned criu_dump_resp__field_indices_by_name[] = {
  0,   /* field[0] = restored */
};
static const ProtobufCIntRange criu_dump_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor criu_dump_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "criu_dump_resp",
  "CriuDumpResp",
  "CriuDumpResp",
  "",
  sizeof(CriuDumpResp),
  1,
  criu_dump_resp__field_descriptors,
  criu_dump_resp__field_indices_by_name,
  1,  criu_dump_resp__number_ranges,
  (ProtobufCMessageInit) criu_dump_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor criu_restore_resp__field_descriptors[1] =
{
  {
    "pid",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuRestoreResp, pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned criu_restore_resp__field_indices_by_name[] = {
  0,   /* field[0] = pid */
};
static const ProtobufCIntRange criu_restore_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor criu_restore_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "criu_restore_resp",
  "CriuRestoreResp",
  "CriuRestoreResp",
  "",
  sizeof(CriuRestoreResp),
  1,
  criu_restore_resp__field_descriptors,
  criu_restore_resp__field_indices_by_name,
  1,  criu_restore_resp__number_ranges,
  (ProtobufCMessageInit) criu_restore_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor criu_notify__field_descriptors[2] =
{
  {
    "script",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuNotify, script),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pid",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CriuNotify, has_pid),
    PROTOBUF_C_OFFSETOF(CriuNotify, pid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned criu_notify__field_indices_by_name[] = {
  1,   /* field[1] = pid */
  0,   /* field[0] = script */
};
static const ProtobufCIntRange criu_notify__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor criu_notify__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "criu_notify",
  "CriuNotify",
  "CriuNotify",
  "",
  sizeof(CriuNotify),
  2,
  criu_notify__field_descriptors,
  criu_notify__field_indices_by_name,
  1,  criu_notify__number_ranges,
  (ProtobufCMessageInit) criu_notify__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor criu_features__field_descriptors[1] =
{
  {
    "mem_track",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuFeatures, has_mem_track),
    PROTOBUF_C_OFFSETOF(CriuFeatures, mem_track),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned criu_features__field_indices_by_name[] = {
  0,   /* field[0] = mem_track */
};
static const ProtobufCIntRange criu_features__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor criu_features__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "criu_features",
  "CriuFeatures",
  "CriuFeatures",
  "",
  sizeof(CriuFeatures),
  1,
  criu_features__field_descriptors,
  criu_features__field_indices_by_name,
  1,  criu_features__number_ranges,
  (ProtobufCMessageInit) criu_features__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor criu_req__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuReq, type),
    &criu_req_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opts",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuReq, opts),
    &criu_opts__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notify_success",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuReq, has_notify_success),
    PROTOBUF_C_OFFSETOF(CriuReq, notify_success),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keep_open",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(CriuReq, has_keep_open),
    PROTOBUF_C_OFFSETOF(CriuReq, keep_open),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "features",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuReq, features),
    &criu_features__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned criu_req__field_indices_by_name[] = {
  4,   /* field[4] = features */
  3,   /* field[3] = keep_open */
  2,   /* field[2] = notify_success */
  1,   /* field[1] = opts */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange criu_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor criu_req__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "criu_req",
  "CriuReq",
  "CriuReq",
  "",
  sizeof(CriuReq),
  5,
  criu_req__field_descriptors,
  criu_req__field_indices_by_name,
  1,  criu_req__number_ranges,
  (ProtobufCMessageInit) criu_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor criu_resp__field_descriptors[8] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuResp, type),
    &criu_req_type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "success",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuResp, success),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dump",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuResp, dump),
    &criu_dump_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "restore",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuResp, restore),
    &criu_restore_resp__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "notify",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuResp, notify),
    &criu_notify__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ps",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuResp, ps),
    &criu_page_server_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cr_errno",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(CriuResp, has_cr_errno),
    PROTOBUF_C_OFFSETOF(CriuResp, cr_errno),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "features",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(CriuResp, features),
    &criu_features__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned criu_resp__field_indices_by_name[] = {
  6,   /* field[6] = cr_errno */
  2,   /* field[2] = dump */
  7,   /* field[7] = features */
  4,   /* field[4] = notify */
  5,   /* field[5] = ps */
  3,   /* field[3] = restore */
  1,   /* field[1] = success */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange criu_resp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor criu_resp__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "criu_resp",
  "CriuResp",
  "CriuResp",
  "",
  sizeof(CriuResp),
  8,
  criu_resp__field_descriptors,
  criu_resp__field_indices_by_name,
  1,  criu_resp__number_ranges,
  (ProtobufCMessageInit) criu_resp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue criu_cg_mode__enum_values_by_number[7] =
{
  { "IGNORE", "CRIU_CG_MODE__IGNORE", 0 },
  { "NONE", "CRIU_CG_MODE__NONE", 1 },
  { "PROPS", "CRIU_CG_MODE__PROPS", 2 },
  { "SOFT", "CRIU_CG_MODE__SOFT", 3 },
  { "FULL", "CRIU_CG_MODE__FULL", 4 },
  { "STRICT", "CRIU_CG_MODE__STRICT", 5 },
  { "DEFAULT", "CRIU_CG_MODE__DEFAULT", 6 },
};
static const ProtobufCIntRange criu_cg_mode__value_ranges[] = {
{0, 0},{0, 7}
};
const ProtobufCEnumValueIndex criu_cg_mode__enum_values_by_name[7] =
{
  { "DEFAULT", 6 },
  { "FULL", 4 },
  { "IGNORE", 0 },
  { "NONE", 1 },
  { "PROPS", 2 },
  { "SOFT", 3 },
  { "STRICT", 5 },
};
const ProtobufCEnumDescriptor criu_cg_mode__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "criu_cg_mode",
  "criu_cg_mode",
  "CriuCgMode",
  "",
  7,
  criu_cg_mode__enum_values_by_number,
  7,
  criu_cg_mode__enum_values_by_name,
  1,
  criu_cg_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
const ProtobufCEnumValue criu_req_type__enum_values_by_number[10] =
{
  { "EMPTY", "CRIU_REQ_TYPE__EMPTY", 0 },
  { "DUMP", "CRIU_REQ_TYPE__DUMP", 1 },
  { "RESTORE", "CRIU_REQ_TYPE__RESTORE", 2 },
  { "CHECK", "CRIU_REQ_TYPE__CHECK", 3 },
  { "PRE_DUMP", "CRIU_REQ_TYPE__PRE_DUMP", 4 },
  { "PAGE_SERVER", "CRIU_REQ_TYPE__PAGE_SERVER", 5 },
  { "NOTIFY", "CRIU_REQ_TYPE__NOTIFY", 6 },
  { "CPUINFO_DUMP", "CRIU_REQ_TYPE__CPUINFO_DUMP", 7 },
  { "CPUINFO_CHECK", "CRIU_REQ_TYPE__CPUINFO_CHECK", 8 },
  { "FEATURE_CHECK", "CRIU_REQ_TYPE__FEATURE_CHECK", 9 },
};
static const ProtobufCIntRange criu_req_type__value_ranges[] = {
{0, 0},{0, 10}
};
const ProtobufCEnumValueIndex criu_req_type__enum_values_by_name[10] =
{
  { "CHECK", 3 },
  { "CPUINFO_CHECK", 8 },
  { "CPUINFO_DUMP", 7 },
  { "DUMP", 1 },
  { "EMPTY", 0 },
  { "FEATURE_CHECK", 9 },
  { "NOTIFY", 6 },
  { "PAGE_SERVER", 5 },
  { "PRE_DUMP", 4 },
  { "RESTORE", 2 },
};
const ProtobufCEnumDescriptor criu_req_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "criu_req_type",
  "criu_req_type",
  "CriuReqType",
  "",
  10,
  criu_req_type__enum_values_by_number,
  10,
  criu_req_type__enum_values_by_name,
  1,
  criu_req_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
