/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "sk-inet.pb-c.h"
void   ip_opts_entry__init
                     (IpOptsEntry         *message)
{
  static IpOptsEntry init_value = IP_OPTS_ENTRY__INIT;
  *message = init_value;
}
size_t ip_opts_entry__get_packed_size
                     (const IpOptsEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ip_opts_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ip_opts_entry__pack
                     (const IpOptsEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ip_opts_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ip_opts_entry__pack_to_buffer
                     (const IpOptsEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ip_opts_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
IpOptsEntry *
       ip_opts_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (IpOptsEntry *)
     protobuf_c_message_unpack (&ip_opts_entry__descriptor,
                                allocator, len, data);
}
void   ip_opts_entry__free_unpacked
                     (IpOptsEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &ip_opts_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   inet_sk_entry__init
                     (InetSkEntry         *message)
{
  static InetSkEntry init_value = INET_SK_ENTRY__INIT;
  *message = init_value;
}
size_t inet_sk_entry__get_packed_size
                     (const InetSkEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inet_sk_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t inet_sk_entry__pack
                     (const InetSkEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inet_sk_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t inet_sk_entry__pack_to_buffer
                     (const InetSkEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inet_sk_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
InetSkEntry *
       inet_sk_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (InetSkEntry *)
     protobuf_c_message_unpack (&inet_sk_entry__descriptor,
                                allocator, len, data);
}
void   inet_sk_entry__free_unpacked
                     (InetSkEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &inet_sk_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ip_opts_entry__field_descriptors[1] =
{
  {
    "freebind",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(IpOptsEntry, has_freebind),
    PROTOBUF_C_OFFSETOF(IpOptsEntry, freebind),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ip_opts_entry__field_indices_by_name[] = {
  0,   /* field[0] = freebind */
};
static const ProtobufCIntRange ip_opts_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ip_opts_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "ip_opts_entry",
  "IpOptsEntry",
  "IpOptsEntry",
  "",
  sizeof(IpOptsEntry),
  1,
  ip_opts_entry__field_descriptors,
  ip_opts_entry__field_indices_by_name,
  1,  ip_opts_entry__number_ranges,
  (ProtobufCMessageInit) ip_opts_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor inet_sk_entry__field_descriptors[17] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ino",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, ino),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "family",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, family),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, proto),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, state),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_port",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, src_port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_port",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, dst_port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flags",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, flags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "backlog",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, backlog),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_addr",
    11,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(InetSkEntry, n_src_addr),
    PROTOBUF_C_OFFSETOF(InetSkEntry, src_addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dst_addr",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(InetSkEntry, n_dst_addr),
    PROTOBUF_C_OFFSETOF(InetSkEntry, dst_addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fown",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, fown),
    &fown_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opts",
    14,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, opts),
    &sk_opts_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "v6only",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(InetSkEntry, has_v6only),
    PROTOBUF_C_OFFSETOF(InetSkEntry, v6only),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip_opts",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, ip_opts),
    &ip_opts_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ifname",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(InetSkEntry, ifname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned inet_sk_entry__field_indices_by_name[] = {
  9,   /* field[9] = backlog */
  11,   /* field[11] = dst_addr */
  7,   /* field[7] = dst_port */
  2,   /* field[2] = family */
  8,   /* field[8] = flags */
  12,   /* field[12] = fown */
  0,   /* field[0] = id */
  16,   /* field[16] = ifname */
  1,   /* field[1] = ino */
  15,   /* field[15] = ip_opts */
  13,   /* field[13] = opts */
  4,   /* field[4] = proto */
  10,   /* field[10] = src_addr */
  6,   /* field[6] = src_port */
  5,   /* field[5] = state */
  3,   /* field[3] = type */
  14,   /* field[14] = v6only */
};
static const ProtobufCIntRange inet_sk_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor inet_sk_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "inet_sk_entry",
  "InetSkEntry",
  "InetSkEntry",
  "",
  sizeof(InetSkEntry),
  17,
  inet_sk_entry__field_descriptors,
  inet_sk_entry__field_indices_by_name,
  1,  inet_sk_entry__number_ranges,
  (ProtobufCMessageInit) inet_sk_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
