/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "sk-packet.pb-c.h"
void   sk_packet_entry__init
                     (SkPacketEntry         *message)
{
  static SkPacketEntry init_value = SK_PACKET_ENTRY__INIT;
  *message = init_value;
}
size_t sk_packet_entry__get_packed_size
                     (const SkPacketEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sk_packet_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sk_packet_entry__pack
                     (const SkPacketEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sk_packet_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sk_packet_entry__pack_to_buffer
                     (const SkPacketEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sk_packet_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SkPacketEntry *
       sk_packet_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SkPacketEntry *)
     protobuf_c_message_unpack (&sk_packet_entry__descriptor,
                                allocator, len, data);
}
void   sk_packet_entry__free_unpacked
                     (SkPacketEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &sk_packet_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sk_packet_entry__field_descriptors[2] =
{
  {
    "id_for",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SkPacketEntry, id_for),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "length",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(SkPacketEntry, length),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sk_packet_entry__field_indices_by_name[] = {
  0,   /* field[0] = id_for */
  1,   /* field[1] = length */
};
static const ProtobufCIntRange sk_packet_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor sk_packet_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "sk_packet_entry",
  "SkPacketEntry",
  "SkPacketEntry",
  "",
  sizeof(SkPacketEntry),
  2,
  sk_packet_entry__field_descriptors,
  sk_packet_entry__field_indices_by_name,
  1,  sk_packet_entry__number_ranges,
  (ProtobufCMessageInit) sk_packet_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
