/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_stats_2eproto__INCLUDED
#define PROTOBUF_C_stats_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _DumpStatsEntry DumpStatsEntry;
typedef struct _RestoreStatsEntry RestoreStatsEntry;
typedef struct _StatsEntry StatsEntry;


/* --- enums --- */


/* --- messages --- */

struct  _DumpStatsEntry
{
  ProtobufCMessage base;
  uint32_t freezing_time;
  uint32_t frozen_time;
  uint32_t memdump_time;
  uint32_t memwrite_time;
  uint64_t pages_scanned;
  uint64_t pages_skipped_parent;
  uint64_t pages_written;
  protobuf_c_boolean has_irmap_resolve;
  uint32_t irmap_resolve;
};
#define DUMP_STATS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&dump_stats_entry__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0,0 }


struct  _RestoreStatsEntry
{
  ProtobufCMessage base;
  uint64_t pages_compared;
  uint64_t pages_skipped_cow;
  uint32_t forking_time;
  uint32_t restore_time;
  protobuf_c_boolean has_pages_restored;
  uint64_t pages_restored;
};
#define RESTORE_STATS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&restore_stats_entry__descriptor) \
    , 0, 0, 0, 0, 0,0 }


struct  _StatsEntry
{
  ProtobufCMessage base;
  DumpStatsEntry *dump;
  RestoreStatsEntry *restore;
};
#define STATS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&stats_entry__descriptor) \
    , NULL, NULL }


/* DumpStatsEntry methods */
void   dump_stats_entry__init
                     (DumpStatsEntry         *message);
size_t dump_stats_entry__get_packed_size
                     (const DumpStatsEntry   *message);
size_t dump_stats_entry__pack
                     (const DumpStatsEntry   *message,
                      uint8_t             *out);
size_t dump_stats_entry__pack_to_buffer
                     (const DumpStatsEntry   *message,
                      ProtobufCBuffer     *buffer);
DumpStatsEntry *
       dump_stats_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   dump_stats_entry__free_unpacked
                     (DumpStatsEntry *message,
                      ProtobufCAllocator *allocator);
/* RestoreStatsEntry methods */
void   restore_stats_entry__init
                     (RestoreStatsEntry         *message);
size_t restore_stats_entry__get_packed_size
                     (const RestoreStatsEntry   *message);
size_t restore_stats_entry__pack
                     (const RestoreStatsEntry   *message,
                      uint8_t             *out);
size_t restore_stats_entry__pack_to_buffer
                     (const RestoreStatsEntry   *message,
                      ProtobufCBuffer     *buffer);
RestoreStatsEntry *
       restore_stats_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   restore_stats_entry__free_unpacked
                     (RestoreStatsEntry *message,
                      ProtobufCAllocator *allocator);
/* StatsEntry methods */
void   stats_entry__init
                     (StatsEntry         *message);
size_t stats_entry__get_packed_size
                     (const StatsEntry   *message);
size_t stats_entry__pack
                     (const StatsEntry   *message,
                      uint8_t             *out);
size_t stats_entry__pack_to_buffer
                     (const StatsEntry   *message,
                      ProtobufCBuffer     *buffer);
StatsEntry *
       stats_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   stats_entry__free_unpacked
                     (StatsEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DumpStatsEntry_Closure)
                 (const DumpStatsEntry *message,
                  void *closure_data);
typedef void (*RestoreStatsEntry_Closure)
                 (const RestoreStatsEntry *message,
                  void *closure_data);
typedef void (*StatsEntry_Closure)
                 (const StatsEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor dump_stats_entry__descriptor;
extern const ProtobufCMessageDescriptor restore_stats_entry__descriptor;
extern const ProtobufCMessageDescriptor stats_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_stats_2eproto__INCLUDED */
