/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_tcp_2dstream_2eproto__INCLUDED
#define PROTOBUF_C_tcp_2dstream_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "opts.pb-c.h"

typedef struct _TcpStreamEntry TcpStreamEntry;


/* --- enums --- */


/* --- messages --- */

struct  _TcpStreamEntry
{
  ProtobufCMessage base;
  uint32_t inq_len;
  uint32_t inq_seq;
  uint32_t outq_len;
  uint32_t outq_seq;
  uint32_t opt_mask;
  uint32_t snd_wscale;
  uint32_t mss_clamp;
  protobuf_c_boolean has_rcv_wscale;
  uint32_t rcv_wscale;
  protobuf_c_boolean has_timestamp;
  uint32_t timestamp;
  protobuf_c_boolean has_cork;
  protobuf_c_boolean cork;
  protobuf_c_boolean has_nodelay;
  protobuf_c_boolean nodelay;
  protobuf_c_boolean has_unsq_len;
  uint32_t unsq_len;
};
#define TCP_STREAM_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tcp_stream_entry__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0,0, 0,0, 0,0, 0,0, 0,0 }


/* TcpStreamEntry methods */
void   tcp_stream_entry__init
                     (TcpStreamEntry         *message);
size_t tcp_stream_entry__get_packed_size
                     (const TcpStreamEntry   *message);
size_t tcp_stream_entry__pack
                     (const TcpStreamEntry   *message,
                      uint8_t             *out);
size_t tcp_stream_entry__pack_to_buffer
                     (const TcpStreamEntry   *message,
                      ProtobufCBuffer     *buffer);
TcpStreamEntry *
       tcp_stream_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tcp_stream_entry__free_unpacked
                     (TcpStreamEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TcpStreamEntry_Closure)
                 (const TcpStreamEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor tcp_stream_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_tcp_2dstream_2eproto__INCLUDED */
