/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_timerfd_2eproto__INCLUDED
#define PROTOBUF_C_timerfd_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "opts.pb-c.h"
#include "fown.pb-c.h"

typedef struct _TimerfdEntry TimerfdEntry;


/* --- enums --- */


/* --- messages --- */

struct  _TimerfdEntry
{
  ProtobufCMessage base;
  uint32_t id;
  uint32_t flags;
  FownEntry *fown;
  uint32_t clockid;
  uint64_t ticks;
  uint32_t settime_flags;
  uint64_t vsec;
  uint64_t vnsec;
  uint64_t isec;
  uint64_t insec;
};
#define TIMERFD_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&timerfd_entry__descriptor) \
    , 0, 0, NULL, 0, 0, 0, 0, 0, 0, 0 }


/* TimerfdEntry methods */
void   timerfd_entry__init
                     (TimerfdEntry         *message);
size_t timerfd_entry__get_packed_size
                     (const TimerfdEntry   *message);
size_t timerfd_entry__pack
                     (const TimerfdEntry   *message,
                      uint8_t             *out);
size_t timerfd_entry__pack_to_buffer
                     (const TimerfdEntry   *message,
                      ProtobufCBuffer     *buffer);
TimerfdEntry *
       timerfd_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   timerfd_entry__free_unpacked
                     (TimerfdEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TimerfdEntry_Closure)
                 (const TimerfdEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor timerfd_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_timerfd_2eproto__INCLUDED */
