/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_tun_2eproto__INCLUDED
#define PROTOBUF_C_tun_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS

#include "opts.pb-c.h"

typedef struct _TunfileEntry TunfileEntry;
typedef struct _TunLinkEntry TunLinkEntry;


/* --- enums --- */


/* --- messages --- */

struct  _TunfileEntry
{
  ProtobufCMessage base;
  uint32_t id;
  char *netdev;
  protobuf_c_boolean has_detached;
  protobuf_c_boolean detached;
};
#define TUNFILE_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tunfile_entry__descriptor) \
    , 0, NULL, 0,0 }


struct  _TunLinkEntry
{
  ProtobufCMessage base;
  uint32_t flags;
  int32_t owner;
  int32_t group;
  uint32_t vnethdr;
  uint32_t sndbuf;
};
#define TUN_LINK_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tun_link_entry__descriptor) \
    , 0, 0, 0, 0, 0 }


/* TunfileEntry methods */
void   tunfile_entry__init
                     (TunfileEntry         *message);
size_t tunfile_entry__get_packed_size
                     (const TunfileEntry   *message);
size_t tunfile_entry__pack
                     (const TunfileEntry   *message,
                      uint8_t             *out);
size_t tunfile_entry__pack_to_buffer
                     (const TunfileEntry   *message,
                      ProtobufCBuffer     *buffer);
TunfileEntry *
       tunfile_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tunfile_entry__free_unpacked
                     (TunfileEntry *message,
                      ProtobufCAllocator *allocator);
/* TunLinkEntry methods */
void   tun_link_entry__init
                     (TunLinkEntry         *message);
size_t tun_link_entry__get_packed_size
                     (const TunLinkEntry   *message);
size_t tun_link_entry__pack
                     (const TunLinkEntry   *message,
                      uint8_t             *out);
size_t tun_link_entry__pack_to_buffer
                     (const TunLinkEntry   *message,
                      ProtobufCBuffer     *buffer);
TunLinkEntry *
       tun_link_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tun_link_entry__free_unpacked
                     (TunLinkEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*TunfileEntry_Closure)
                 (const TunfileEntry *message,
                  void *closure_data);
typedef void (*TunLinkEntry_Closure)
                 (const TunLinkEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor tunfile_entry__descriptor;
extern const ProtobufCMessageDescriptor tun_link_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_tun_2eproto__INCLUDED */
