/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_userns_2eproto__INCLUDED
#define PROTOBUF_C_userns_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _UidGidExtent UidGidExtent;
typedef struct _UsernsEntry UsernsEntry;


/* --- enums --- */


/* --- messages --- */

struct  _UidGidExtent
{
  ProtobufCMessage base;
  uint32_t first;
  uint32_t lower_first;
  uint32_t count;
};
#define UID_GID_EXTENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&uid_gid_extent__descriptor) \
    , 0, 0, 0 }


struct  _UsernsEntry
{
  ProtobufCMessage base;
  size_t n_uid_map;
  UidGidExtent **uid_map;
  size_t n_gid_map;
  UidGidExtent **gid_map;
};
#define USERNS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&userns_entry__descriptor) \
    , 0,NULL, 0,NULL }


/* UidGidExtent methods */
void   uid_gid_extent__init
                     (UidGidExtent         *message);
size_t uid_gid_extent__get_packed_size
                     (const UidGidExtent   *message);
size_t uid_gid_extent__pack
                     (const UidGidExtent   *message,
                      uint8_t             *out);
size_t uid_gid_extent__pack_to_buffer
                     (const UidGidExtent   *message,
                      ProtobufCBuffer     *buffer);
UidGidExtent *
       uid_gid_extent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   uid_gid_extent__free_unpacked
                     (UidGidExtent *message,
                      ProtobufCAllocator *allocator);
/* UsernsEntry methods */
void   userns_entry__init
                     (UsernsEntry         *message);
size_t userns_entry__get_packed_size
                     (const UsernsEntry   *message);
size_t userns_entry__pack
                     (const UsernsEntry   *message,
                      uint8_t             *out);
size_t userns_entry__pack_to_buffer
                     (const UsernsEntry   *message,
                      ProtobufCBuffer     *buffer);
UsernsEntry *
       userns_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   userns_entry__free_unpacked
                     (UsernsEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*UidGidExtent_Closure)
                 (const UidGidExtent *message,
                  void *closure_data);
typedef void (*UsernsEntry_Closure)
                 (const UsernsEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor uid_gid_extent__descriptor;
extern const ProtobufCMessageDescriptor userns_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_userns_2eproto__INCLUDED */
