/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_utsns_2eproto__INCLUDED
#define PROTOBUF_C_utsns_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _UtsnsEntry UtsnsEntry;


/* --- enums --- */


/* --- messages --- */

struct  _UtsnsEntry
{
  ProtobufCMessage base;
  char *nodename;
  char *domainname;
};
#define UTSNS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&utsns_entry__descriptor) \
    , NULL, NULL }


/* UtsnsEntry methods */
void   utsns_entry__init
                     (UtsnsEntry         *message);
size_t utsns_entry__get_packed_size
                     (const UtsnsEntry   *message);
size_t utsns_entry__pack
                     (const UtsnsEntry   *message,
                      uint8_t             *out);
size_t utsns_entry__pack_to_buffer
                     (const UtsnsEntry   *message,
                      ProtobufCBuffer     *buffer);
UtsnsEntry *
       utsns_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   utsns_entry__free_unpacked
                     (UtsnsEntry *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*UtsnsEntry_Closure)
                 (const UtsnsEntry *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor utsns_entry__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_utsns_2eproto__INCLUDED */
