/* Autogenerated, do not edit */
#ifndef __CR_VERSION_H__
#define __CR_VERSION_H__
#define CRIU_VERSION "2.4"
#define CRIU_VERSION_MAJOR  2
#define CRIU_VERSION_MINOR  4
#define CRIU_GITID "v2.4-70-g9c7a234"
#endif /* __CR_VERSION_H__ */
