/* Autogenerated, do not edit */
#ifndef __CR_VERSION_H__
#define __CR_VERSION_H__
#define CRIU_VERSION "2.4"
#define CRIU_VERSION_MAJOR  2
#define CRIU_VERSION_MINOR  4
#define CRIU_GITID "63f0280"
#endif /* __CR_VERSION_H__ */
